-- ==============================================================================
-- Thinkatic Enterprise Database Schema Migration for Supabase
-- Tables:
--   1. admin_users          (Admin authentication & permissions)
--   2. profiles             (User accounts & authentication profiles)
--   3. contact_submissions  (Leads & inquiries management)
--   4. plans                (Enterprise technology service packages)
--   5. attendance           (User check-in/out attendance tracking)
--   6. kyc_verifications    (Identity KYC verification flow)
--   7. affiliate_referrals  (Affiliate program, referral links & commission)
--   8. wallets              (User wallet balances & accounts)
--   9. wallet_transactions  (Transaction ledger & payout history)
--  10. client_updates       (Private client-specific project communication)
-- Includes: Triggers, Foreign Keys, Indexes, RLS Policies, Seed Data
-- ==============================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. TRIGGER FUNCTION FOR updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ------------------------------------------------------------------------------
-- 1. Table: admin_users
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.admin_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_admin_users_updated_at ON public.admin_users;
CREATE TRIGGER trg_admin_users_updated_at
    BEFORE UPDATE ON public.admin_users
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 2. Table: profiles (User Login & Accounts)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT,
    full_name TEXT,
    avatar_url TEXT,
    role TEXT NOT NULL DEFAULT 'user',
    selected_plan TEXT,
    referral_code TEXT UNIQUE,
    referred_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Idempotent column additions for existing profiles table
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS password_hash TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS selected_plan TEXT;

DROP TRIGGER IF EXISTS trg_profiles_updated_at ON public.profiles;
CREATE TRIGGER trg_profiles_updated_at
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_profiles_email ON public.profiles(email);
CREATE INDEX IF NOT EXISTS idx_profiles_referral_code ON public.profiles(referral_code);

-- ------------------------------------------------------------------------------
-- 3. Table: contact_submissions (Leads)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.contact_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    company TEXT,
    budget TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'new',
    notes TEXT,
    source TEXT DEFAULT 'contact_form',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_contact_submissions_updated_at ON public.contact_submissions;
CREATE TRIGGER trg_contact_submissions_updated_at
    BEFORE UPDATE ON public.contact_submissions
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_contact_submissions_status ON public.contact_submissions(status);
CREATE INDEX IF NOT EXISTS idx_contact_submissions_created_at ON public.contact_submissions(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_contact_submissions_email ON public.contact_submissions(email);

-- ------------------------------------------------------------------------------
-- 4. Table: plans (Enterprise Technology Plans)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id TEXT NOT NULL UNIQUE,
    service_number TEXT NOT NULL DEFAULT '00',
    category TEXT NOT NULL DEFAULT 'AI & Automation',
    name TEXT NOT NULL,
    price INTEGER NOT NULL DEFAULT 0,
    tag TEXT NOT NULL DEFAULT '',
    description TEXT NOT NULL DEFAULT '',
    features JSONB NOT NULL DEFAULT '[]'::jsonb,
    popular BOOLEAN NOT NULL DEFAULT false,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_plans_updated_at ON public.plans;
CREATE TRIGGER trg_plans_updated_at
    BEFORE UPDATE ON public.plans
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE UNIQUE INDEX IF NOT EXISTS idx_plans_service_id ON public.plans(service_id);
CREATE INDEX IF NOT EXISTS idx_plans_category ON public.plans(category);
CREATE INDEX IF NOT EXISTS idx_plans_sort_order ON public.plans(sort_order);

-- ------------------------------------------------------------------------------
-- 5. Table: attendance (Attendance Tracking)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    check_out TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'present',
    duration_minutes INTEGER DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_user_attendance_date UNIQUE (user_id, date)
);

DROP TRIGGER IF EXISTS trg_attendance_updated_at ON public.attendance;
CREATE TRIGGER trg_attendance_updated_at
    BEFORE UPDATE ON public.attendance
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_attendance_user_id ON public.attendance(user_id);
CREATE INDEX IF NOT EXISTS idx_attendance_date ON public.attendance(date DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_status ON public.attendance(status);

-- ------------------------------------------------------------------------------
-- 6. Table: kyc_verifications (Identity Verification)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.kyc_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    full_name TEXT NOT NULL,
    date_of_birth DATE,
    country TEXT NOT NULL DEFAULT 'US',
    document_type TEXT NOT NULL DEFAULT 'passport',
    document_number TEXT NOT NULL,
    document_front_url TEXT,
    document_back_url TEXT,
    selfie_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    rejection_reason TEXT,
    reviewed_by TEXT,
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_kyc_updated_at ON public.kyc_verifications;
CREATE TRIGGER trg_kyc_updated_at
    BEFORE UPDATE ON public.kyc_verifications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_kyc_user_id ON public.kyc_verifications(user_id);
CREATE INDEX IF NOT EXISTS idx_kyc_status ON public.kyc_verifications(status);

-- ------------------------------------------------------------------------------
-- 7. Table: affiliate_referrals (Affiliate Program)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.affiliate_referrals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    referrer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    referred_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    referral_code TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    commission_rate NUMERIC(5,2) NOT NULL DEFAULT 10.00,
    total_reward NUMERIC(12,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_affiliate_updated_at ON public.affiliate_referrals;
CREATE TRIGGER trg_affiliate_updated_at
    BEFORE UPDATE ON public.affiliate_referrals
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_affiliate_referrer ON public.affiliate_referrals(referrer_id);
CREATE INDEX IF NOT EXISTS idx_affiliate_code ON public.affiliate_referrals(referral_code);

-- ------------------------------------------------------------------------------
-- 8. Table: wallets (User Wallets)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wallets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE UNIQUE,
    balance NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    pending_balance NUMERIC(14,2) NOT NULL DEFAULT 0.00,
    currency TEXT NOT NULL DEFAULT 'USD',
    is_locked BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_wallets_updated_at ON public.wallets;
CREATE TRIGGER trg_wallets_updated_at
    BEFORE UPDATE ON public.wallets
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_wallets_user ON public.wallets(user_id);

-- ------------------------------------------------------------------------------
-- 9. Table: wallet_transactions (Transaction Ledger)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.wallet_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES public.wallets(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    amount NUMERIC(14,2) NOT NULL,
    fee NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    status TEXT NOT NULL DEFAULT 'completed',
    description TEXT NOT NULL,
    reference_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet ON public.wallet_transactions(wallet_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_user ON public.wallet_transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_type ON public.wallet_transactions(type);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_created ON public.wallet_transactions(created_at DESC);

-- ------------------------------------------------------------------------------
-- 10. Table: purchases (server-verified PayPal purchases)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    package_id TEXT NOT NULL,
    package_name TEXT NOT NULL,
    paypal_order_id TEXT NOT NULL UNIQUE,
    paypal_capture_id TEXT UNIQUE,
    amount NUMERIC(14,2) NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PAID', 'CANCELLED', 'FAILED')),
    purchased_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_purchases_user ON public.purchases(user_id);
CREATE INDEX IF NOT EXISTS idx_purchases_status ON public.purchases(status);

DROP TRIGGER IF EXISTS trg_purchases_updated_at ON public.purchases;
CREATE TRIGGER trg_purchases_updated_at
    BEFORE UPDATE ON public.purchases
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 11. Table: payout_details (encrypted user payout destinations)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.payout_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    method TEXT NOT NULL CHECK (method IN ('paypal', 'indian_bank')),
    details_encrypted TEXT NOT NULL,
    display_label TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, method)
);

DROP TRIGGER IF EXISTS trg_payout_details_updated_at ON public.payout_details;
CREATE TRIGGER trg_payout_details_updated_at
    BEFORE UPDATE ON public.payout_details
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 12. Table: withdrawals (BPO-only payout requests)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    amount NUMERIC(14,2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    method TEXT NOT NULL CHECK (method IN ('paypal', 'indian_bank')),
    payout_details_id BIGINT NOT NULL REFERENCES public.payout_details(id),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    rejection_reason TEXT,
    reviewed_by BIGINT REFERENCES public.admin_users(id),
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user ON public.withdrawals(user_id);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON public.withdrawals(status);

DROP TRIGGER IF EXISTS trg_withdrawals_updated_at ON public.withdrawals;
CREATE TRIGGER trg_withdrawals_updated_at
    BEFORE UPDATE ON public.withdrawals
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------------------------
-- 10. Table: client_updates (Private Client Communication)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.client_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    created_by TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_client_updates_updated_at ON public.client_updates;
CREATE TRIGGER trg_client_updates_updated_at
    BEFORE UPDATE ON public.client_updates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_client_updates_user_id ON public.client_updates(user_id);
CREATE INDEX IF NOT EXISTS idx_client_updates_status ON public.client_updates(status);
CREATE INDEX IF NOT EXISTS idx_client_updates_published_at ON public.client_updates(published_at DESC);

ALTER TABLE public.client_updates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read their own published updates" ON public.client_updates;
CREATE POLICY "Users read their own published updates"
    ON public.client_updates FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND status = 'published');

-- ------------------------------------------------------------------------------
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------------------------

-- Enable RLS across all tables
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kyc_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.affiliate_referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payout_details ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

-- 1. admin_users RLS
DROP POLICY IF EXISTS "Allow service role full access on admin_users" ON public.admin_users;
CREATE POLICY "Allow service role full access on admin_users"
    ON public.admin_users FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 2. profiles RLS
DROP POLICY IF EXISTS "Allow users read own profile" ON public.profiles;
CREATE POLICY "Allow users read own profile"
    ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);

DROP POLICY IF EXISTS "Allow users update own profile" ON public.profiles;
CREATE POLICY "Allow users update own profile"
    ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Allow service role full access on profiles" ON public.profiles;
CREATE POLICY "Allow service role full access on profiles"
    ON public.profiles FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. contact_submissions RLS
DROP POLICY IF EXISTS "Allow public insert on contact_submissions" ON public.contact_submissions;
CREATE POLICY "Allow public insert on contact_submissions"
    ON public.contact_submissions FOR INSERT TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow service role full access on contact_submissions" ON public.contact_submissions;
CREATE POLICY "Allow service role full access on contact_submissions"
    ON public.contact_submissions FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. plans RLS
DROP POLICY IF EXISTS "Allow public read access on plans" ON public.plans;
CREATE POLICY "Allow public read access on plans"
    ON public.plans FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow service role full access on plans" ON public.plans;
CREATE POLICY "Allow service role full access on plans"
    ON public.plans FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. attendance RLS
DROP POLICY IF EXISTS "Allow users read own attendance" ON public.attendance;
CREATE POLICY "Allow users read own attendance"
    ON public.attendance FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow service role full access on attendance" ON public.attendance;
CREATE POLICY "Allow service role full access on attendance"
    ON public.attendance FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 6. kyc_verifications RLS
DROP POLICY IF EXISTS "Allow users read own kyc" ON public.kyc_verifications;
CREATE POLICY "Allow users read own kyc"
    ON public.kyc_verifications FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users insert own kyc" ON public.kyc_verifications;
CREATE POLICY "Allow users insert own kyc"
    ON public.kyc_verifications FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow service role full access on kyc_verifications" ON public.kyc_verifications;
CREATE POLICY "Allow service role full access on kyc_verifications"
    ON public.kyc_verifications FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 7. affiliate_referrals RLS
DROP POLICY IF EXISTS "Allow users read own referrals" ON public.affiliate_referrals;
CREATE POLICY "Allow users read own referrals"
    ON public.affiliate_referrals FOR SELECT TO authenticated USING (auth.uid() = referrer_id);

DROP POLICY IF EXISTS "Allow service role full access on affiliate_referrals" ON public.affiliate_referrals;
CREATE POLICY "Allow service role full access on affiliate_referrals"
    ON public.affiliate_referrals FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 8. wallets RLS
DROP POLICY IF EXISTS "Allow users read own wallet" ON public.wallets;
CREATE POLICY "Allow users read own wallet"
    ON public.wallets FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow service role full access on wallets" ON public.wallets;
CREATE POLICY "Allow service role full access on wallets"
    ON public.wallets FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 9. wallet_transactions RLS
DROP POLICY IF EXISTS "Allow users read own transactions" ON public.wallet_transactions;
CREATE POLICY "Allow users read own transactions"
    ON public.wallet_transactions FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow service role full access on wallet_transactions" ON public.wallet_transactions;
CREATE POLICY "Allow service role full access on wallet_transactions"
    ON public.wallet_transactions FOR ALL TO service_role USING (true) WITH CHECK (true);

-- Purchases, payout details, and withdrawals are accessed through the API.
DROP POLICY IF EXISTS "Allow service role full access on purchases" ON public.purchases;
CREATE POLICY "Allow service role full access on purchases"
    ON public.purchases FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow service role full access on payout_details" ON public.payout_details;
CREATE POLICY "Allow service role full access on payout_details"
    ON public.payout_details FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow service role full access on withdrawals" ON public.withdrawals;
CREATE POLICY "Allow service role full access on withdrawals"
    ON public.withdrawals FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ------------------------------------------------------------------------------
-- SEED DATA
-- ------------------------------------------------------------------------------

-- 1. Default Admin User (username: admin, default password: admin123)
INSERT INTO public.admin_users (username, password_hash)
VALUES ('admin', '$2b$10$LDx3HIdCL5NkVUc7.ftRbeLK/YVxzSBQ0x6bpIJVLUzWrD45QMeDy')
ON CONFLICT (username) DO NOTHING;

-- 2. 16 Flagship Enterprise Technology Plans
INSERT INTO public.plans (service_id, service_number, category, name, price, tag, description, features, popular, sort_order)
VALUES
    -- A. AI & Automation
    ('ai-launch', '01', 'AI & Automation', 'AI Launch', 25000, 'Targeted Entry',
     'For companies ready to introduce AI into a single important business function.',
     '["AI readiness assessment", "AI strategy & roadmap", "1 AI-powered workflow", "Custom AI application/agent", "LLM integration", "Knowledge base / RAG", "Business system integration", "Security baseline", "Analytics dashboard", "Deployment", "30 days post-launch support"]'::jsonb,
     false, 0),
    ('ai-transformation', '02', 'AI & Automation', 'AI Transformation', 75000, 'Most Popular',
     'For companies looking to automate multiple business processes with AI.',
     '["Everything in AI Launch", "3-5 AI agents/workflows", "CRM/ERP integrations", "Advanced automation", "Document intelligence", "Customer-service automation", "Sales automation", "Internal AI copilot", "Advanced analytics", "Role-based access", "AI governance framework", "Production infrastructure", "90 days optimization & support"]'::jsonb,
     true, 1),
    ('enterprise-ai', '03', 'AI & Automation', 'Enterprise AI', 150000, 'Enterprise Scale',
     'For enterprises and organizations with complex technology environments.',
     '["Enterprise AI strategy", "AI architecture", "Multi-agent AI systems", "Private AI environment", "Enterprise RAG", "Multiple business integrations", "Custom AI applications", "AI governance", "Security architecture", "Data pipelines", "Model evaluation", "Monitoring", "Compliance-ready architecture", "Cloud deployment", "Dedicated engineering team", "6 months optimization"]'::jsonb,
     false, 2),

    -- B. Cloud & Modernization
    ('cloud-modernization', '04', 'Cloud & Modernization', 'Cloud Modernization', 100000, 'Infrastructure Scale',
     'Migrate, re-architect, and optimize workloads across AWS, Azure, and Google Cloud.',
     '["Infrastructure assessment", "Cloud strategy", "AWS / Azure / Google Cloud architecture", "Application migration", "Database migration", "API modernization", "DevOps implementation", "CI/CD", "Infrastructure automation", "Security hardening", "Monitoring", "Disaster recovery", "Performance optimization"]'::jsonb,
     false, 3),
    ('legacy-transformation', '05', 'Cloud & Modernization', 'Legacy Transformation', 150000, 'System Modernization',
     'Deconstruct monoliths, modernize legacy codebases, and eliminate critical technical debt.',
     '["Legacy application audit", "Architecture redesign", "Code modernization", "Database modernization", "API development", "Cloud migration", "UI modernization", "Testing automation", "Security modernization", "AI integration", "Deployment", "Knowledge transfer", "Long-term support"]'::jsonb,
     false, 4),
    ('enterprise-transformation', '06', 'Cloud & Modernization', 'Enterprise Transformation', 300000, 'Flagship Strategic Engagement',
     'For organizations requiring a complete technology transformation.',
     '["Technology assessment", "Digital transformation strategy", "Legacy modernization", "Cloud transformation", "AI implementation", "Data modernization", "Cybersecurity", "Enterprise integrations", "DevOps", "Custom software engineering", "Technology governance", "Dedicated transformation team", "12-month roadmap"]'::jsonb,
     true, 5),

    -- C. Cybersecurity
    ('cybersecurity-foundation', '07', 'Cybersecurity', 'Cybersecurity Foundation', 50000, 'Essential Defense',
     'Establish essential enterprise security controls, IAM, and risk posture.',
     '["Security assessment", "Vulnerability assessment", "IAM", "Endpoint security", "Network security", "Cloud security", "Security policies", "Risk assessment", "Security roadmap"]'::jsonb,
     false, 6),
    ('enterprise-security', '08', 'Cybersecurity', 'Enterprise Security', 125000, 'Zero Trust Architecture',
     'Implement complete Zero Trust architecture, SIEM integration, and incident response.',
     '["Zero Trust architecture", "Cloud security", "Identity & access management", "SIEM", "Security monitoring", "Vulnerability management", "Incident response", "Security automation", "Compliance support", "Security operations"]'::jsonb,
     false, 7),
    ('ai-security', '09', 'Cybersecurity', 'AI Security', 100000, 'LLM & GenAI Defense',
     'Harden LLMs, agents, and generative systems against prompt injection and data leaks.',
     '["AI security assessment", "LLM security", "Data-leakage prevention", "Prompt-injection protection", "AI access controls", "Model security", "AI monitoring", "AI governance", "Security testing", "Enterprise AI security architecture"]'::jsonb,
     false, 8),

    -- D. Data & Analytics
    ('data-foundation', '10', 'Data & Analytics', 'Data Foundation', 75000, 'Single Source of Truth',
     'Unify fragmented data sources into a modern data warehouse with automated ETL.',
     '["Data architecture", "Data warehouse", "Data pipelines", "ETL/ELT", "Data integration", "Data quality", "Business dashboards", "Reporting"]'::jsonb,
     false, 9),
    ('enterprise-data-platform', '11', 'Data & Analytics', 'Enterprise Data Platform', 150000, 'Lakehouse & Real-Time',
     'Build an AI-ready data lakehouse capable of real-time analytics and predictive ML pipelines.',
     '["Data lake/lakehouse", "Real-time data", "Enterprise data warehouse", "Data governance", "Data engineering", "Advanced analytics", "BI", "AI-ready data architecture", "Cloud data infrastructure"]'::jsonb,
     false, 10),

    -- E. Product Engineering
    ('digital-product-development', '12', 'Product Engineering', 'Digital Product Development', 50000, 'Full-Lifecycle Build',
     'Engineer mission-critical digital products from architecture through production deployment.',
     '["Product strategy", "UX/UI", "Architecture", "Web application", "Mobile application", "Backend", "APIs", "Cloud infrastructure", "QA", "Security", "Deployment"]'::jsonb,
     false, 11),
    ('enterprise-product-engineering', '13', 'Product Engineering', 'Enterprise Product Engineering', 150000, 'Dedicated Squad',
     'Deploy a dedicated senior engineering team to architect and build complex systems.',
     '["Product discovery", "Enterprise architecture", "UX/UI", "Web & mobile", "Backend systems", "API ecosystem", "Cloud", "Data", "AI integration", "Cybersecurity", "DevOps", "QA automation", "Dedicated engineering team"]'::jsonb,
     false, 12),

    -- F. Managed Services
    ('managed-ai', '14', 'Managed Services', 'Managed AI', 10000, 'Continuous AI Ops ($10k/mo)',
     'Ongoing AI agent optimization, model management, infrastructure, and latency monitoring.',
     '["AI monitoring", "Agent optimization", "Model management", "AI infrastructure", "Performance monitoring", "Security monitoring", "Continuous improvements", "Support"]'::jsonb,
     false, 13),
    ('managed-cloud', '15', 'Managed Services', 'Managed Cloud', 10000, '24/7 Cloud Operations ($10k/mo)',
     '24/7 cloud monitoring, infrastructure management, disaster recovery, and cost governance.',
     '["Cloud monitoring", "Infrastructure management", "DevOps", "Security", "Backup", "Disaster recovery", "Cost optimization", "24/7 monitoring"]'::jsonb,
     false, 14),
    ('managed-cybersecurity', '16', 'Managed Services', 'Managed Cybersecurity', 15000, 'SOC & Threat Hunting ($15k/mo)',
     'Continuous security monitoring, threat detection, vulnerability management, and incident response.',
     '["Security monitoring", "Threat detection", "Vulnerability management", "Incident response", "Security reporting", "Security operations", "Continuous risk assessment"]'::jsonb,
     false, 15)
ON CONFLICT (service_id) DO UPDATE SET
    service_number = EXCLUDED.service_number,
    category       = EXCLUDED.category,
    name           = EXCLUDED.name,
    price          = EXCLUDED.price,
    tag            = EXCLUDED.tag,
    description    = EXCLUDED.description,
    features       = EXCLUDED.features,
    popular        = EXCLUDED.popular,
    sort_order     = EXCLUDED.sort_order;
