export interface ServicePackageDefinition {
  serviceId: string;
  serviceNumber: string;
  category: "BUILD" | "AUTOMATE" | "AI" | "SCALE" | "OPERATE";
  serviceName: string;
  name: string;
  tier?: string;
  price: number;
  priceMax?: number | null;
  priceDisplay: string;
  pricingType: "fixed" | "range" | "custom";
  currency: "USD";
  billingInterval: "one_time" | "monthly";
  tag: string;
  description: string;
  targetCustomer: string;
  features: string[];
  deliveryTimeline: string;
  supportDuration: string;
  includedUnits?: string | null;
  popular?: boolean;
  sortOrder: number;
  enabled: boolean;
  clientVisible: boolean;
}

export const AUTHORITATIVE_CATALOGUE: ServicePackageDefinition[] = [
  // =========================================================================
  // BUILD (9 Packages)
  // =========================================================================
  // A. Business Website Development
  {
    serviceId: "web-starter",
    serviceNumber: "01",
    category: "BUILD",
    serviceName: "Business Website Development",
    name: "STARTER",
    tier: "STARTER",
    price: 499,
    priceDisplay: "$499",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Small Business Entry",
    description: "Ideal for small businesses, consultants, and local businesses establishing a modern, high-converting digital presence.",
    targetCustomer: "Small businesses, consultants, local businesses",
    deliveryTimeline: "5–7 days",
    supportDuration: "7 days post-launch support",
    features: [
      "3–4 pages",
      "Custom responsive design",
      "Mobile + desktop optimization",
      "Contact form",
      "WhatsApp/call integration",
      "Google Maps",
      "Basic on-page SEO",
      "Social media links",
      "SSL setup",
      "7 days post-launch support",
    ],
    sortOrder: 1,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "web-professional",
    serviceNumber: "02",
    category: "BUILD",
    serviceName: "Business Website Development",
    name: "PROFESSIONAL",
    tier: "PROFESSIONAL",
    price: 999,
    priceDisplay: "$999",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Most Popular",
    description: "For growing businesses requiring premium UI/UX, conversion animations, lead forms, and search console optimization.",
    targetCustomer: "Growing businesses",
    deliveryTimeline: "7–14 days",
    supportDuration: "30 days support",
    features: [
      "Everything in Starter",
      "5–8 pages",
      "Premium UI/UX",
      "Custom animations",
      "Blog/news section",
      "Lead-generation forms",
      "Google Analytics",
      "Search Console setup",
      "Basic technical SEO",
      "Speed optimization",
      "30 days support",
    ],
    sortOrder: 2,
    popular: true,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "web-premium",
    serviceNumber: "03",
    category: "BUILD",
    serviceName: "Business Website Development",
    name: "PREMIUM",
    tier: "PREMIUM",
    price: 1999,
    priceDisplay: "$1,999",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Enterprise Grade",
    description: "For established companies needing 10–15 fully custom pages, CRM integration, advanced SEO, and ongoing performance tuning.",
    targetCustomer: "Established companies",
    deliveryTimeline: "14–21 days",
    supportDuration: "90 days support",
    features: [
      "Everything in Professional",
      "10–15 pages",
      "Fully custom design",
      "Advanced animations",
      "Interactive sections",
      "Advanced SEO structure",
      "Conversion optimization",
      "CRM integration",
      "Third-party API integrations",
      "Performance optimization",
      "90 days support",
      "$99–$299/month maintenance upsell",
    ],
    sortOrder: 3,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // B. Shopify / E-commerce
  {
    serviceId: "shopify-launch",
    serviceNumber: "04",
    category: "BUILD",
    serviceName: "Shopify / E-commerce",
    name: "LAUNCH",
    tier: "LAUNCH",
    price: 999,
    priceDisplay: "$999",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Store Launch",
    description: "Turnkey Shopify store setup with theme customization, payment and shipping configuration, and up to 20 products.",
    targetCustomer: "Emerging e-commerce brands",
    deliveryTimeline: "7–10 days",
    supportDuration: "14 days support",
    features: [
      "Shopify setup",
      "Theme customization",
      "Up to 20 products",
      "Payment setup",
      "Shipping configuration",
      "Basic pages",
      "Mobile optimization",
      "Analytics",
      "Basic SEO",
    ],
    sortOrder: 4,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "shopify-grow",
    serviceNumber: "05",
    category: "BUILD",
    serviceName: "Shopify / E-commerce",
    name: "GROW",
    tier: "GROW",
    price: 1999,
    priceDisplay: "$1,999",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Store Expansion",
    description: "Custom storefront with up to 100 products, product filtering, customer reviews, and abandoned-cart automation.",
    targetCustomer: "Expanding online stores",
    deliveryTimeline: "2–3 weeks",
    supportDuration: "30 days support",
    features: [
      "Everything in Launch",
      "Custom storefront",
      "Up to 100 products",
      "Product filtering",
      "Reviews",
      "Email integration",
      "Marketing integrations",
      "Abandoned-cart setup",
      "Analytics",
      "Conversion optimization",
    ],
    sortOrder: 5,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "shopify-scale",
    serviceNumber: "06",
    category: "BUILD",
    serviceName: "Shopify / E-commerce",
    name: "SCALE",
    tier: "SCALE",
    price: 3999,
    priceDisplay: "$3,999+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Enterprise Commerce",
    description: "High-volume commerce with custom ERP/CRM integrations, large product catalog, checkout automations, and 90-day support.",
    targetCustomer: "High-volume & omni-channel retailers",
    deliveryTimeline: "3–4 weeks",
    supportDuration: "90-day support",
    features: [
      "Premium custom design",
      "Large product catalog",
      "Advanced integrations",
      "ERP/CRM integration",
      "Custom functionality",
      "Automation",
      "Advanced analytics",
      "Conversion optimization",
      "90-day support",
    ],
    sortOrder: 6,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // C. Custom Software Development
  {
    serviceId: "custom-mvp",
    serviceNumber: "07",
    category: "BUILD",
    serviceName: "Custom Software Development",
    name: "MVP",
    tier: "MVP",
    price: 3999,
    priceDisplay: "$3,999+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Startup Validation",
    description: "Validate product hypotheses rapidly with full UI/UX, frontend, backend API, database, authentication, and cloud deployment.",
    targetCustomer: "Startups testing an idea",
    deliveryTimeline: "4–8 weeks",
    supportDuration: "30 days support",
    features: [
      "Requirements analysis",
      "UI/UX",
      "Frontend",
      "Backend",
      "Database",
      "Authentication",
      "Admin panel",
      "API integration",
      "Cloud deployment",
      "Basic testing",
    ],
    sortOrder: 7,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "custom-business",
    serviceNumber: "08",
    category: "BUILD",
    serviceName: "Custom Software Development",
    name: "BUSINESS",
    tier: "BUSINESS",
    price: 9999,
    priceDisplay: "$9,999+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Production Web App",
    description: "Custom web application with advanced dashboard, user management, payment integrations, notification pipelines, and analytics.",
    targetCustomer: "Scaling businesses needing bespoke software",
    deliveryTimeline: "8–16 weeks",
    supportDuration: "60 days support",
    features: [
      "Custom web application",
      "Advanced dashboard",
      "User management",
      "Payment integration",
      "APIs",
      "Notifications",
      "Admin system",
      "Analytics",
      "Security",
      "QA",
      "Cloud deployment",
    ],
    sortOrder: 8,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "custom-enterprise",
    serviceNumber: "09",
    category: "BUILD",
    serviceName: "Custom Software Development",
    name: "ENTERPRISE",
    tier: "ENTERPRISE",
    price: 20000,
    priceDisplay: "$20,000+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Enterprise Platform",
    description: "Complex multi-role web platform with third-party enterprise integrations, DevOps automation, and dedicated engineering team.",
    targetCustomer: "Complex multi-tier corporate operations",
    deliveryTimeline: "12–24 weeks",
    supportDuration: "Dedicated project team",
    features: [
      "Complex application",
      "Multiple user roles",
      "Advanced workflows",
      "Third-party integrations",
      "Enterprise security",
      "Scalable architecture",
      "DevOps",
      "Automated testing",
      "Dedicated project team",
    ],
    sortOrder: 9,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // =========================================================================
  // AUTOMATE (3 Packages)
  // =========================================================================
  // D. Business Automation
  {
    serviceId: "auto-starter",
    serviceNumber: "10",
    category: "AUTOMATE",
    serviceName: "Business Automation",
    name: "AUTOMATE STARTER",
    tier: "AUTOMATE STARTER",
    price: 499,
    priceDisplay: "$499",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Process Starter",
    description: "Eliminate repetitive manual entry by automating one core business process with forms, email triggers, and spreadsheet sync.",
    targetCustomer: "Small businesses needing initial automation",
    deliveryTimeline: "3–5 days",
    supportDuration: "14 days support",
    features: [
      "1 business process",
      "Form automation",
      "Email automation",
      "Basic notifications",
      "Google Sheets/CRM integration",
    ],
    sortOrder: 10,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "auto-business",
    serviceNumber: "11",
    category: "AUTOMATE",
    serviceName: "Business Automation",
    name: "AUTOMATE BUSINESS",
    tier: "AUTOMATE BUSINESS",
    price: 1499,
    priceDisplay: "$1,499",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Multi-Process System",
    description: "Connect 3–5 operational workflows including CRM lead management, SMS alerts, bi-directional data sync, and weekly reporting.",
    targetCustomer: "Multi-department operations",
    deliveryTimeline: "7–14 days",
    supportDuration: "30 days support",
    features: [
      "3–5 workflows",
      "CRM automation",
      "Lead management",
      "Email/SMS automation",
      "Data synchronization",
      "Reporting",
      "API integrations",
    ],
    sortOrder: 11,
    popular: true,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "auto-pro",
    serviceNumber: "12",
    category: "AUTOMATE",
    serviceName: "Business Automation",
    name: "AUTOMATE PRO",
    tier: "AUTOMATE PRO",
    price: 3499,
    priceDisplay: "$3,499+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Full-Stack Automation",
    description: "10+ workflows across CRM and ERP systems, document processing, multi-level approvals, and active error monitoring.",
    targetCustomer: "Complex enterprise workflows",
    deliveryTimeline: "2–4 weeks",
    supportDuration: "60 days support",
    features: [
      "10+ workflows",
      "AI automation",
      "CRM + ERP integrations",
      "Automated reporting",
      "Document processing",
      "Approval workflows",
      "Advanced API integrations",
      "Monitoring",
    ],
    sortOrder: 12,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // =========================================================================
  // SCALE (9 Packages)
  // =========================================================================
  // E. QA & Software Testing
  {
    serviceId: "qa-starter",
    serviceNumber: "13",
    category: "SCALE",
    serviceName: "QA & Software Testing",
    name: "QA STARTER",
    tier: "QA STARTER",
    price: 499,
    priceDisplay: "$499",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Launch QA Audit",
    description: "Thorough pre-launch audit covering functional, responsive, and cross-browser testing with comprehensive bug summary.",
    targetCustomer: "Pre-release audit & launch readiness",
    deliveryTimeline: "3–5 days",
    supportDuration: "7 days support",
    features: [
      "Website/app testing",
      "Functional testing",
      "Responsive testing",
      "Browser testing",
      "Bug report",
      "Test summary",
    ],
    sortOrder: 13,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "qa-business",
    serviceNumber: "14",
    category: "SCALE",
    serviceName: "QA & Software Testing",
    name: "QA BUSINESS",
    tier: "QA BUSINESS",
    price: 999,
    priceDisplay: "$999/month",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Ongoing QA Retainer",
    description: "Continuous monthly quality assurance covering regression, mobile, browser, and API testing with weekly executive reports.",
    targetCustomer: "Continuous sprint & staging quality assurance",
    deliveryTimeline: "Ongoing / Monthly",
    supportDuration: "Monthly ongoing",
    features: [
      "Manual testing",
      "Regression testing",
      "Mobile testing",
      "Browser testing",
      "API testing",
      "Test documentation",
      "Weekly reports",
    ],
    sortOrder: 14,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "qa-team",
    serviceNumber: "15",
    category: "SCALE",
    serviceName: "QA & Software Testing",
    name: "QA TEAM",
    tier: "QA TEAM",
    price: 2499,
    priceDisplay: "$2,499+/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Dedicated QA Squad",
    description: "Dedicated QA squad providing manual + automation frameworks, API, performance, CI/CD integration, and a dedicated QA manager.",
    targetCustomer: "Dedicated end-to-end testing squads",
    deliveryTimeline: "Ongoing / Monthly",
    supportDuration: "Dedicated QA manager",
    features: [
      "Dedicated QA resources",
      "Manual + automation testing",
      "API testing",
      "Performance testing",
      "Regression testing",
      "CI/CD integration",
      "Continuous testing",
      "Dedicated QA manager",
    ],
    sortOrder: 15,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // F. Dedicated Developers
  {
    serviceId: "dev-developer",
    serviceNumber: "16",
    category: "SCALE",
    serviceName: "Dedicated Developers",
    name: "DEVELOPER",
    tier: "DEVELOPER",
    price: 1999,
    priceMax: 3499,
    priceDisplay: "$1,999–$3,499/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "160 Hours / Month",
    description: "1 dedicated full-time developer (160 hrs/month) with daily communication, Git/GitHub integration, and weekly project reporting.",
    targetCustomer: "Teams needing full-time dev augmentation",
    includedUnits: "160 hours/month",
    deliveryTimeline: "Immediate allocation",
    supportDuration: "Monthly ongoing",
    features: [
      "Dedicated developer",
      "160 hours/month",
      "Daily communication",
      "Git/GitHub",
      "Weekly reporting",
      "Project management",
    ],
    sortOrder: 16,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "dev-team",
    serviceNumber: "17",
    category: "SCALE",
    serviceName: "Dedicated Developers",
    name: "DEVELOPMENT TEAM",
    tier: "DEVELOPMENT TEAM",
    price: 5999,
    priceMax: 9999,
    priceDisplay: "$5,999–$9,999/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "2–4 Devs + PM + QA",
    description: "Complete product development squad of 2–4 developers, dedicated project manager, QA, and UI/UX support.",
    targetCustomer: "Complete product delivery squads",
    includedUnits: "2–4 developers + PM + QA",
    deliveryTimeline: "1–2 weeks onboarding",
    supportDuration: "Dedicated Slack/Teams channel",
    features: [
      "2–4 developers",
      "Project manager",
      "QA support",
      "UI/UX support",
      "Weekly reporting",
      "Dedicated Slack/Teams channel",
    ],
    sortOrder: 17,
    popular: true,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "dev-product-team",
    serviceNumber: "18",
    category: "SCALE",
    serviceName: "Dedicated Developers",
    name: "PRODUCT TEAM",
    tier: "PRODUCT TEAM",
    price: 10000,
    priceMax: 20000,
    priceDisplay: "$10,000–$20,000+/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Full Turnkey Squad",
    description: "Autonomous turnkey delivery squad: Product Manager, Senior UI/UX Designer, Full-Stack Developers, QA, and DevOps Engineer.",
    targetCustomer: "Full turnkey product engineering",
    includedUnits: "Cross-functional product squad",
    deliveryTimeline: "2 weeks onboarding",
    supportDuration: "Dedicated project management",
    features: [
      "Product manager",
      "UI/UX designer",
      "Developers",
      "QA",
      "DevOps",
      "Dedicated project management",
    ],
    sortOrder: 18,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // G. BPO / Customer Support (Numbered 19, 20, 21 under SCALE)
  {
    serviceId: "bpo-agent",
    serviceNumber: "19",
    category: "SCALE",
    serviceName: "BPO / Customer Support",
    name: "CUSTOMER SUPPORT AGENT",
    tier: "CUSTOMER SUPPORT AGENT",
    price: 699,
    priceMax: 1199,
    priceDisplay: "$699–$1,199/agent/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Dedicated Agent",
    description: "Dedicated support agent for email, live chat, and ticket resolution with defined shifts and daily performance metrics.",
    targetCustomer: "Businesses needing dedicated customer support",
    includedUnits: "1 dedicated agent (160 hrs)",
    deliveryTimeline: "3–5 days onboarding",
    supportDuration: "Monthly ongoing",
    features: [
      "Email support",
      "Chat support",
      "Ticket management",
      "Customer queries",
      "Basic reporting",
      "Defined working hours",
    ],
    sortOrder: 19,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "bpo-premium-support",
    serviceNumber: "20",
    category: "SCALE",
    serviceName: "BPO / Customer Support",
    name: "PREMIUM SUPPORT",
    tier: "PREMIUM SUPPORT",
    price: 1200,
    priceMax: 1800,
    priceDisplay: "$1,200–$1,800/agent/month",
    pricingType: "range",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Omnichannel Support",
    description: "Senior agent providing voice, chat, and email support with dedicated supervisor, QA scorecards, and CRM pipeline management.",
    targetCustomer: "Multi-channel high-touch customer operations",
    includedUnits: "1 senior agent + supervisor",
    deliveryTimeline: "5–7 days onboarding",
    supportDuration: "Dedicated supervisor",
    features: [
      "Voice + chat + email",
      "CRM management",
      "Escalation management",
      "Quality monitoring",
      "Reporting",
      "Dedicated supervisor",
    ],
    sortOrder: 20,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "bpo-team",
    serviceNumber: "21",
    category: "SCALE",
    serviceName: "BPO / Customer Support",
    name: "BPO TEAM",
    tier: "BPO TEAM",
    price: 0,
    priceDisplay: "Custom Pricing",
    pricingType: "custom",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Turnkey Operations",
    description: "Scalable squad of 5+ agents, dedicated Team Leader, QA Analyst, and Operations Manager under strict SLA governance.",
    targetCustomer: "Large-scale customer service operations",
    includedUnits: "5+ agents + team lead + QA",
    deliveryTimeline: "1–2 weeks onboarding",
    supportDuration: "SLA-based delivery",
    features: [
      "5+ agents",
      "Team leader",
      "QA",
      "Operations manager",
      "Performance dashboard",
      "SLA-based delivery",
    ],
    sortOrder: 21,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // =========================================================================
  // OPERATE (3 Packages)
  // =========================================================================
  // H. Website Maintenance (Numbered 22, 23, 24 under OPERATE)
  {
    serviceId: "maint-basic",
    serviceNumber: "22",
    category: "OPERATE",
    serviceName: "Website Maintenance",
    name: "BASIC",
    tier: "BASIC",
    price: 99,
    priceDisplay: "$99/month",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Site Guardian",
    description: "Essential monthly website health: uptime monitoring, cloud backups, security updates, minor bugfixes, and 1 developer hour.",
    targetCustomer: "Essential website upkeep",
    includedUnits: "1 hour development/month",
    deliveryTimeline: "Ongoing / Monthly",
    supportDuration: "Monthly ongoing",
    features: [
      "Website monitoring",
      "Backups",
      "Security updates",
      "Minor fixes",
      "1 hour development/month",
    ],
    sortOrder: 22,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "maint-business",
    serviceNumber: "23",
    category: "OPERATE",
    serviceName: "Website Maintenance",
    name: "BUSINESS",
    tier: "BUSINESS",
    price: 199,
    priceDisplay: "$199/month",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Pro Active Care",
    description: "Everything in Basic plus 3 hours development, regular content updates, continuous performance and SEO monitoring, and monthly report.",
    targetCustomer: "Active business websites",
    includedUnits: "3 hours development/month",
    deliveryTimeline: "Ongoing / Monthly",
    supportDuration: "Monthly ongoing",
    features: [
      "Everything in Basic",
      "3 hours development",
      "Content updates",
      "Performance monitoring",
      "SEO monitoring",
      "Monthly report",
    ],
    sortOrder: 23,
    popular: true,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "maint-premium",
    serviceNumber: "24",
    category: "OPERATE",
    serviceName: "Website Maintenance",
    name: "PREMIUM",
    tier: "PREMIUM",
    price: 399,
    priceDisplay: "$399/month",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "monthly",
    tag: "Mission Critical",
    description: "Everything in Business plus 8 hours development, priority SLAs, advanced speed optimization, security monitoring, and conversion tuning.",
    targetCustomer: "Mission-critical web applications",
    includedUnits: "8 hours development/month",
    deliveryTimeline: "Ongoing / Monthly",
    supportDuration: "Priority support",
    features: [
      "Everything in Business",
      "8 hours development",
      "Priority support",
      "Advanced optimization",
      "Security monitoring",
      "Conversion improvements",
    ],
    sortOrder: 24,
    popular: false,
    enabled: true,
    clientVisible: true,
  },

  // =========================================================================
  // AI (5 Packages)
  // =========================================================================
  // I. AI Solutions & Automation
  {
    serviceId: "ai-starter",
    serviceNumber: "25",
    category: "AI",
    serviceName: "AI Solutions",
    name: "AI STARTER",
    tier: "STARTER",
    price: 999,
    priceDisplay: "$999",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Website AI Chatbot",
    description: "Website AI chatbot with company knowledge base, FAQ automation, lead collection, conversation flows, and analytics.",
    targetCustomer: "Businesses adding automated website conversational AI",
    deliveryTimeline: "7–10 days",
    supportDuration: "30 days support",
    features: [
      "Website AI chatbot",
      "Company knowledge base",
      "FAQ automation",
      "Lead collection",
      "Basic conversation flows",
      "Email notifications",
      "Analytics",
      "Deployment",
    ],
    sortOrder: 25,
    popular: true,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "ai-business",
    serviceNumber: "26",
    category: "AI",
    serviceName: "AI Solutions",
    name: "AI BUSINESS",
    tier: "BUSINESS",
    price: 2499,
    priceDisplay: "$2,499",
    pricingType: "fixed",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Multichannel AI Agent",
    description: "Includes everything in AI Starter plus advanced AI agent, document integration, CRM, appointment booking, WhatsApp, and workflows.",
    targetCustomer: "Growing businesses needing multichannel autonomous AI workflows",
    deliveryTimeline: "2–3 weeks",
    supportDuration: "60 days support",
    features: [
      "Everything in AI Starter",
      "Advanced AI agent",
      "Document/knowledge-base integration",
      "Lead qualification",
      "Appointment booking",
      "CRM integration",
      "WhatsApp integration",
      "Email integration",
      "Conversation analytics",
      "Custom business workflows",
    ],
    sortOrder: 26,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "ai-enterprise",
    serviceNumber: "27",
    category: "AI",
    serviceName: "Enterprise AI Ecosystem",
    name: "AI ENTERPRISE",
    tier: "ENTERPRISE",
    price: 5000,
    priceMax: null,
    priceDisplay: "From $5,000+",
    pricingType: "range",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Multi-Agent & Voice AI",
    description: "Multiple AI agents, Voice AI, CRM/ERP integration, human handoff, monitoring, and ongoing optimization. Recurring: $299–$1,500+/month depending on usage.",
    targetCustomer: "Enterprises needing bespoke multi-agent and voice AI infrastructure",
    includedUnits: "Recurring: $299–$1,500+/month depending on usage",
    deliveryTimeline: "4–8 weeks",
    supportDuration: "Dedicated SLA & ongoing optimization",
    features: [
      "Multiple AI agents",
      "Voice AI",
      "Customer-support automation",
      "Sales automation",
      "CRM/ERP integration",
      "Custom APIs",
      "Advanced workflows",
      "Admin dashboard",
      "Human handoff",
      "Monitoring",
      "Ongoing optimization",
    ],
    sortOrder: 27,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "ai-automation",
    serviceNumber: "28",
    category: "AI",
    serviceName: "AI Business Automation",
    name: "AI AUTOMATION",
    tier: "AUTOMATION",
    price: 0,
    priceDisplay: "Custom Pricing",
    pricingType: "custom",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Intelligent Workflow Automation",
    description: "End-to-end AI workflow automation, intelligent document processing, approval flows, and ERP/CRM integrations.",
    targetCustomer: "Companies automating operational processes with AI models",
    deliveryTimeline: "Scope dependent",
    supportDuration: "Included with implementation SLA",
    features: [
      "AI workflow automation",
      "AI-powered business processes",
      "CRM/ERP integrations",
      "Automated reporting",
      "Document processing",
      "Approval workflows",
      "Advanced API integrations",
      "Monitoring",
    ],
    sortOrder: 28,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
  {
    serviceId: "voice-ai",
    serviceNumber: "29",
    category: "AI",
    serviceName: "Conversational Voice AI",
    name: "VOICE AI",
    tier: "VOICE",
    price: 0,
    priceDisplay: "Custom Pricing / Included in AI Enterprise",
    pricingType: "custom",
    currency: "USD",
    billingInterval: "one_time",
    tag: "Autonomous Voice Agents",
    description: "Sub-second latency voice AI agents for inbound customer service and outbound conversational qualification. Included in AI Enterprise or available via Custom Scope.",
    targetCustomer: "Contact centres and high-touch customer support operations",
    deliveryTimeline: "Scope dependent",
    supportDuration: "Included with implementation SLA",
    features: [
      "Voice AI",
      "Included in AI Enterprise",
      "Customer support automation",
      "Sales automation",
      "Human handoff",
      "Monitoring",
      "Integration options",
    ],
    sortOrder: 29,
    popular: false,
    enabled: true,
    clientVisible: true,
  },
];

export const LEGACY_DEPRECATED_PLANS = new Set([
  "ai-launch",
  "ai-transformation",
  "enterprise-ai",
  "ai launch",
  "ai transformation",
  "enterprise ai",
]);

export const AI_EXCLUDED_PLANS = LEGACY_DEPRECATED_PLANS;

