-- ==============================================================================
-- Migration: 20261003000000_agent_bpo_conversations.sql
-- Description: Agent <-> BPO Partner/Supervisor Operational Messaging System
-- ==============================================================================

CREATE TABLE IF NOT EXISTS public.agent_bpo_conversations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  subject TEXT NOT NULL DEFAULT 'Operations Support',
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'resolved', 'archived')),
  last_message_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_message_preview TEXT,
  unread_agent_count INTEGER NOT NULL DEFAULT 0,
  unread_bpo_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.agent_bpo_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id BIGINT NOT NULL REFERENCES public.agent_bpo_conversations(id) ON DELETE CASCADE,
  sender_type TEXT NOT NULL CHECK (sender_type IN ('agent', 'bpo_supervisor')),
  sender_id TEXT NOT NULL,
  sender_name TEXT NOT NULL,
  message TEXT NOT NULL,
  attachment_url TEXT,
  attachment_name TEXT,
  attachment_type TEXT,
  read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for high-speed scoped queries
CREATE INDEX IF NOT EXISTS idx_agent_bpo_conv_agent ON public.agent_bpo_conversations(agent_id);
CREATE INDEX IF NOT EXISTS idx_agent_bpo_conv_partner ON public.agent_bpo_conversations(partner_id);
CREATE INDEX IF NOT EXISTS idx_agent_bpo_conv_updated ON public.agent_bpo_conversations(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_bpo_messages_conv ON public.agent_bpo_messages(conversation_id, created_at ASC);

-- Row Level Security
ALTER TABLE public.agent_bpo_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agent_bpo_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "agent_bpo_conversations service role access" ON public.agent_bpo_conversations;
CREATE POLICY "agent_bpo_conversations service role access" ON public.agent_bpo_conversations
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "agent_bpo_messages service role access" ON public.agent_bpo_messages;
CREATE POLICY "agent_bpo_messages service role access" ON public.agent_bpo_messages
  FOR ALL TO service_role USING (true) WITH CHECK (true);
