-- Additive Meetings and project collaboration domain.
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('meetings', TRUE)
ON CONFLICT (module_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    related_ticket_id BIGINT REFERENCES public.tickets(id) ON DELETE SET NULL,
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 200),
    description TEXT,
    meeting_type TEXT NOT NULL DEFAULT 'project_meeting' CHECK (meeting_type IN ('project_meeting','requirement_discussion','review','demo','uat','planning','support','other')),
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','confirmed','in_progress','completed','cancelled','rescheduled','no_show')),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    location TEXT,
    agenda TEXT,
    cancellation_reason TEXT,
    organizer_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    created_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT meeting_time_order CHECK (ends_at > starts_at)
);

CREATE TABLE IF NOT EXISTS public.meeting_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE CASCADE,
    participant_role TEXT NOT NULL DEFAULT 'participant' CHECK (participant_role IN ('organizer','client','team','participant')),
    rsvp_status TEXT NOT NULL DEFAULT 'pending' CHECK (rsvp_status IN ('pending','accepted','declined','tentative')),
    responded_at TIMESTAMPTZ,
    client_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT meeting_participant_identity_check CHECK ((user_id IS NOT NULL) <> (admin_id IS NOT NULL)),
    CONSTRAINT meeting_participant_unique_user UNIQUE (meeting_id, user_id),
    CONSTRAINT meeting_participant_unique_admin UNIQUE (meeting_id, admin_id)
);

CREATE TABLE IF NOT EXISTS public.meeting_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 3 AND 200),
    preferred_starts_at TIMESTAMPTZ NOT NULL,
    preferred_ends_at TIMESTAMPTZ NOT NULL,
    timezone TEXT NOT NULL DEFAULT 'UTC',
    reason TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'requested' CHECK (status IN ('requested','pending_review','scheduled','confirmed','rejected','rescheduled')),
    reviewed_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    review_notes TEXT,
    meeting_id BIGINT REFERENCES public.meetings(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT meeting_request_time_order CHECK (preferred_ends_at > preferred_starts_at)
);

CREATE TABLE IF NOT EXISTS public.meeting_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
    author_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    note_type TEXT NOT NULL DEFAULT 'summary' CHECK (note_type IN ('summary','discussion','decision','next_steps')),
    body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 20000),
    client_visible BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT meeting_note_author_check CHECK ((author_user_id IS NOT NULL) <> (author_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.meeting_action_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    assigned_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 300),
    description TEXT,
    due_date DATE,
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','critical')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','in_progress','completed','cancelled')),
    created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.meeting_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
    minutes_before INTEGER NOT NULL CHECK (minutes_before IN (1440,60,15)),
    notify_at TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    UNIQUE (meeting_id, minutes_before)
);

CREATE INDEX IF NOT EXISTS idx_meetings_client ON public.meetings(client_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_meetings_project ON public.meetings(project_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_meetings_status ON public.meetings(status, starts_at);
CREATE INDEX IF NOT EXISTS idx_meeting_participants_user ON public.meeting_participants(user_id, meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_participants_admin ON public.meeting_participants(admin_id, meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_requests_client ON public.meeting_requests(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meeting_notes_meeting ON public.meeting_notes(meeting_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meeting_action_items_project ON public.meeting_action_items(project_id, status, due_date);
CREATE INDEX IF NOT EXISTS idx_meeting_reminders_due ON public.meeting_reminders(notify_at) WHERE sent_at IS NULL;

DROP TRIGGER IF EXISTS trg_meetings_updated_at ON public.meetings;
CREATE TRIGGER trg_meetings_updated_at BEFORE UPDATE ON public.meetings FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_meeting_requests_updated_at ON public.meeting_requests;
CREATE TRIGGER trg_meeting_requests_updated_at BEFORE UPDATE ON public.meeting_requests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_meeting_notes_updated_at ON public.meeting_notes;
CREATE TRIGGER trg_meeting_notes_updated_at BEFORE UPDATE ON public.meeting_notes FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_meeting_action_items_updated_at ON public.meeting_action_items;
CREATE TRIGGER trg_meeting_action_items_updated_at BEFORE UPDATE ON public.meeting_action_items FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_action_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meeting_reminders ENABLE ROW LEVEL SECURITY;

DO $$ DECLARE table_name TEXT; BEGIN
  FOREACH table_name IN ARRAY ARRAY['meetings','meeting_participants','meeting_requests','meeting_notes','meeting_action_items','meeting_reminders'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', table_name || ' service role access', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', table_name || ' service role access', table_name);
  END LOOP;
END $$;
