-- =============================================================================
-- Thinkatic Billing, Invoices & Payments Module
-- Additive migration — safe to run on existing deployments.
-- Tables: invoices, invoice_items, invoice_payments, invoice_receipts
-- + invoice_number_seq sequence for sequential unique invoice numbers
-- =============================================================================

-- Module settings seeds
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('billing', TRUE)
ON CONFLICT (module_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- Sequential invoice number generator
-- Produces numbers like INV-2026-000001
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS public.invoice_number_seq
    START WITH 1
    INCREMENT BY 1
    NO MAXVALUE
    NO CYCLE;

-- Function to generate the formatted invoice number
CREATE OR REPLACE FUNCTION public.next_invoice_number()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    seq_val BIGINT;
    year_part TEXT;
BEGIN
    seq_val := nextval('public.invoice_number_seq');
    year_part := to_char(NOW() AT TIME ZONE 'UTC', 'YYYY');
    RETURN 'INV-' || year_part || '-' || lpad(seq_val::TEXT, 6, '0');
END;
$$;

-- ---------------------------------------------------------------------------
-- Table: invoices
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoices (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number      TEXT NOT NULL UNIQUE DEFAULT public.next_invoice_number(),
    client_id           UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    project_id          BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    related_ticket_id   BIGINT REFERENCES public.tickets(id) ON DELETE SET NULL,
    purchase_id         BIGINT REFERENCES public.purchases(id) ON DELETE SET NULL,

    -- Lifecycle: draft → sent → pending_payment → paid | partially_paid → paid
    status              TEXT NOT NULL DEFAULT 'draft'
                            CHECK (status IN (
                                'draft', 'sent', 'pending_payment',
                                'partially_paid', 'paid', 'overdue',
                                'cancelled', 'refunded'
                            )),

    -- Dates
    invoice_date        DATE NOT NULL DEFAULT CURRENT_DATE,
    due_date            DATE NOT NULL,

    -- Amounts — always server-calculated, never trusted from client
    currency            TEXT NOT NULL DEFAULT 'USD',
    subtotal            NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    tax_rate            NUMERIC(6,4) NOT NULL DEFAULT 0 CHECK (tax_rate >= 0 AND tax_rate <= 1),
    tax_amount          NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    discount_amount     NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
    total               NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    amount_paid         NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
    balance_due         NUMERIC(14,2) GENERATED ALWAYS AS (total - amount_paid) STORED,

    -- Metadata
    notes               TEXT,
    terms               TEXT,
    internal_notes      TEXT,   -- admin-only, never exposed to client
    sent_at             TIMESTAMPTZ,
    paid_at             TIMESTAMPTZ,
    cancelled_at        TIMESTAMPTZ,
    cancellation_reason TEXT,

    -- Admin who created / last modified
    created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    updated_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT invoice_due_date_order CHECK (due_date >= invoice_date),
    CONSTRAINT invoice_paid_not_exceed_total CHECK (amount_paid <= total)
);

-- ---------------------------------------------------------------------------
-- Table: invoice_items  (line items)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id      BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    sort_order      INTEGER NOT NULL DEFAULT 0,
    description     TEXT NOT NULL CHECK (char_length(description) BETWEEN 1 AND 500),
    quantity        NUMERIC(10,3) NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price      NUMERIC(14,2) NOT NULL CHECK (unit_price >= 0),
    -- line_total = quantity * unit_price (stored for performance, recalculated on save)
    line_total      NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (line_total >= 0),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Table: invoice_payments  (individual payment transactions against an invoice)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoice_payments (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id          BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    client_id           UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

    amount              NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    currency            TEXT NOT NULL DEFAULT 'USD',

    -- Payment method
    payment_method      TEXT NOT NULL DEFAULT 'manual'
                            CHECK (payment_method IN ('paypal', 'manual', 'bank_transfer', 'wallet', 'other')),
    gateway             TEXT,           -- 'paypal', null for manual
    gateway_order_id    TEXT UNIQUE,    -- PayPal orderId — unique to prevent duplicates
    gateway_capture_id  TEXT UNIQUE,    -- PayPal captureId
    reference           TEXT,           -- Manual reference number / bank reference

    -- Status
    status              TEXT NOT NULL DEFAULT 'initiated'
                            CHECK (status IN (
                                'initiated', 'pending', 'successful',
                                'failed', 'cancelled', 'refunded'
                            )),

    -- Who recorded it (for manual payments)
    recorded_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,

    paid_at             TIMESTAMPTZ,
    notes               TEXT,
    metadata            JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Table: invoice_receipts  (one receipt per successful payment)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invoice_receipts (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number  TEXT NOT NULL UNIQUE,
    invoice_id      BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE RESTRICT,
    payment_id      BIGINT NOT NULL REFERENCES public.invoice_payments(id) ON DELETE RESTRICT,
    client_id       UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,

    amount          NUMERIC(14,2) NOT NULL CHECK (amount > 0),
    currency        TEXT NOT NULL DEFAULT 'USD',

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_invoices_client     ON public.invoices(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_project    ON public.invoices(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoices_status     ON public.invoices(status, due_date);
CREATE INDEX IF NOT EXISTS idx_invoices_due_date   ON public.invoices(due_date) WHERE status NOT IN ('paid','cancelled','refunded');
CREATE INDEX IF NOT EXISTS idx_invoice_items_inv   ON public.invoice_items(invoice_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_invoice_payments_inv   ON public.invoice_payments(invoice_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_payments_cli  ON public.invoice_payments(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_invoice_payments_gw   ON public.invoice_payments(gateway_order_id) WHERE gateway_order_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_invoice_receipts_inv  ON public.invoice_receipts(invoice_id);
CREATE INDEX IF NOT EXISTS idx_invoice_receipts_cli  ON public.invoice_receipts(client_id, created_at DESC);

-- ---------------------------------------------------------------------------
-- updated_at triggers
-- ---------------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_invoices_updated_at ON public.invoices;
CREATE TRIGGER trg_invoices_updated_at
    BEFORE UPDATE ON public.invoices
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trg_invoice_items_updated_at ON public.invoice_items;
CREATE TRIGGER trg_invoice_items_updated_at
    BEFORE UPDATE ON public.invoice_items
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS trg_invoice_payments_updated_at ON public.invoice_payments;
CREATE TRIGGER trg_invoice_payments_updated_at
    BEFORE UPDATE ON public.invoice_payments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ---------------------------------------------------------------------------
-- Row-Level Security
-- ---------------------------------------------------------------------------
ALTER TABLE public.invoices         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_items    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoice_receipts ENABLE ROW LEVEL SECURITY;

DO $$ DECLARE tbl TEXT; BEGIN
  FOREACH tbl IN ARRAY ARRAY[
    'invoices', 'invoice_items', 'invoice_payments', 'invoice_receipts'
  ] LOOP
    EXECUTE format(
      'DROP POLICY IF EXISTS %I ON public.%I',
      tbl || ' service role access', tbl
    );
    EXECUTE format(
      'CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)',
      tbl || ' service role access', tbl
    );
  END LOOP;
END $$;

-- ---------------------------------------------------------------------------
-- Helper: recalculate an invoice's totals from its line items
-- Called server-side after any item mutation
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.recalculate_invoice_totals(p_invoice_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_subtotal      NUMERIC(14,2);
    v_tax_rate      NUMERIC(6,4);
    v_tax_amount    NUMERIC(14,2);
    v_discount      NUMERIC(14,2);
    v_total         NUMERIC(14,2);
BEGIN
    -- Recalculate each line_total
    UPDATE public.invoice_items
    SET line_total = ROUND(quantity * unit_price, 2)
    WHERE invoice_id = p_invoice_id;

    -- Sum subtotal
    SELECT COALESCE(SUM(line_total), 0)
    INTO v_subtotal
    FROM public.invoice_items
    WHERE invoice_id = p_invoice_id;

    -- Fetch current tax_rate and discount from invoice
    SELECT tax_rate, discount_amount
    INTO v_tax_rate, v_discount
    FROM public.invoices
    WHERE id = p_invoice_id;

    v_tax_amount := ROUND(v_subtotal * v_tax_rate, 2);
    v_total      := GREATEST(0, v_subtotal + v_tax_amount - v_discount);

    UPDATE public.invoices
    SET subtotal   = v_subtotal,
        tax_amount = v_tax_amount,
        total      = v_total,
        updated_at = NOW()
    WHERE id = p_invoice_id;
END;
$$;

-- ---------------------------------------------------------------------------
-- Helper: mark overdue invoices (run periodically / on list fetch)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.mark_overdue_invoices()
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE updated_count INTEGER;
BEGIN
    UPDATE public.invoices
    SET status     = 'overdue',
        updated_at = NOW()
    WHERE status IN ('sent', 'pending_payment', 'partially_paid')
      AND due_date < CURRENT_DATE
      AND balance_due > 0;

    GET DIAGNOSTICS updated_count = ROW_COUNT;
    RETURN updated_count;
END;
$$;
