-- Additive private document and project communication domain.
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('documents', TRUE), ('communication', TRUE)
ON CONFLICT (module_key) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('project-documents', 'project-documents', FALSE), ('project-communication', 'project-communication', FALSE)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name TEXT NOT NULL,
    original_file_name TEXT NOT NULL,
    file_type TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0 AND file_size <= 26214400),
    storage_path TEXT NOT NULL UNIQUE,
    category TEXT NOT NULL DEFAULT 'Other',
    description TEXT,
    project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
    milestone_id BIGINT REFERENCES public.project_milestones(id) ON DELETE SET NULL,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    uploaded_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    uploaded_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    visibility TEXT NOT NULL DEFAULT 'client_visible' CHECK (visibility IN ('client_visible','internal_only')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','archived','deleted')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT document_uploader_check CHECK ((uploaded_by_user_id IS NOT NULL) <> (uploaded_by_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.document_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
    actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    actor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 3 AND 200),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','closed','archived')),
    created_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.conversation_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.project_conversations(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT conversation_participant_identity_check CHECK ((user_id IS NOT NULL) <> (admin_id IS NOT NULL)),
    CONSTRAINT conversation_participant_unique_user UNIQUE (conversation_id, user_id),
    CONSTRAINT conversation_participant_unique_admin UNIQUE (conversation_id, admin_id)
);

CREATE TABLE IF NOT EXISTS public.conversation_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL REFERENCES public.project_conversations(id) ON DELETE CASCADE,
    sender_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    sender_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    body TEXT NOT NULL CHECK (char_length(body) BETWEEN 1 AND 10000),
    edited_at TIMESTAMPTZ,
    deleted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT conversation_message_sender_check CHECK ((sender_user_id IS NOT NULL) <> (sender_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.conversation_message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES public.conversation_messages(id) ON DELETE CASCADE,
    uploaded_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    uploaded_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    storage_path TEXT NOT NULL UNIQUE,
    file_name TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0 AND file_size <= 10485760),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT conversation_attachment_uploader_check CHECK ((uploaded_by_user_id IS NOT NULL) <> (uploaded_by_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.conversation_message_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL REFERENCES public.conversation_messages(id) ON DELETE CASCADE,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE CASCADE,
    read_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT conversation_read_identity_check CHECK ((user_id IS NOT NULL) <> (admin_id IS NOT NULL))
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_conversation_reads_user ON public.conversation_message_reads(message_id, user_id) WHERE user_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversation_reads_admin ON public.conversation_message_reads(message_id, admin_id) WHERE admin_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_documents_client ON public.documents(client_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_documents_project ON public.documents(project_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_document_activity_document ON public.document_activity(document_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversations_client ON public.project_conversations(client_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_user ON public.conversation_participants(user_id, conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversation_participants_admin ON public.conversation_participants(admin_id, conversation_id);
CREATE INDEX IF NOT EXISTS idx_conversation_messages_conversation ON public.conversation_messages(conversation_id, created_at);

DROP TRIGGER IF EXISTS trg_documents_updated_at ON public.documents;
CREATE TRIGGER trg_documents_updated_at BEFORE UPDATE ON public.documents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_project_conversations_updated_at ON public.project_conversations;
CREATE TRIGGER trg_project_conversations_updated_at BEFORE UPDATE ON public.project_conversations FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.document_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_message_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_message_reads ENABLE ROW LEVEL SECURITY;

DO $$ DECLARE table_name TEXT; BEGIN
  FOREACH table_name IN ARRAY ARRAY['documents','document_activity','project_conversations','conversation_participants','conversation_messages','conversation_message_attachments','conversation_message_reads'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', table_name || ' service role access', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', table_name || ' service role access', table_name);
  END LOOP;
END $$;
