-- Client-specific project updates. Every row belongs to one authenticated profile.
CREATE TABLE IF NOT EXISTS public.client_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category TEXT,
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    created_by TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_client_updates_updated_at ON public.client_updates;
CREATE TRIGGER trg_client_updates_updated_at
    BEFORE UPDATE ON public.client_updates
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE INDEX IF NOT EXISTS idx_client_updates_user_id ON public.client_updates(user_id);
CREATE INDEX IF NOT EXISTS idx_client_updates_status ON public.client_updates(status);
CREATE INDEX IF NOT EXISTS idx_client_updates_published_at ON public.client_updates(published_at DESC);

ALTER TABLE public.client_updates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users read their own published updates" ON public.client_updates;
CREATE POLICY "Users read their own published updates"
    ON public.client_updates FOR SELECT TO authenticated
    USING (auth.uid() = user_id AND status = 'published');

