-- Additive project management domain.
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('projects', TRUE)
ON CONFLICT (module_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 200),
    project_type TEXT NOT NULL DEFAULT 'Custom Project',
    status TEXT NOT NULL DEFAULT 'planning' CHECK (status IN ('planning','design','development','ai_training','integration','testing','uat','deployment','completed','on_hold','cancelled')),
    progress_percent INTEGER NOT NULL DEFAULT 0 CHECK (progress_percent BETWEEN 0 AND 100),
    manual_progress_percent INTEGER CHECK (manual_progress_percent BETWEEN 0 AND 100),
    start_date DATE,
    expected_end_date DATE,
    budget NUMERIC(14,2),
    description TEXT,
    scope TEXT,
    objectives TEXT,
    technologies JSONB NOT NULL DEFAULT '[]'::jsonb,
    client_visible_team BOOLEAN NOT NULL DEFAULT TRUE,
    created_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    member_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    member_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    member_name TEXT NOT NULL,
    member_role TEXT NOT NULL,
    client_visible BOOLEAN NOT NULL DEFAULT FALSE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT project_member_identity_check CHECK ((member_user_id IS NOT NULL) <> (member_admin_id IS NOT NULL)
        OR (member_user_id IS NULL AND member_admin_id IS NULL))
);

CREATE TABLE IF NOT EXISTS public.project_milestones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    description TEXT,
    start_date DATE,
    due_date DATE,
    status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','in_progress','at_risk','completed','on_hold')),
    completion_percent INTEGER NOT NULL DEFAULT 0 CHECK (completion_percent BETWEEN 0 AND 100),
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    milestone_id BIGINT REFERENCES public.project_milestones(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    assigned_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_name TEXT,
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low','medium','high','critical')),
    status TEXT NOT NULL DEFAULT 'todo' CHECK (status IN ('todo','in_progress','blocked','review','completed')),
    start_date DATE,
    due_date DATE,
    estimated_effort TEXT,
    internal_notes TEXT,
    client_visible BOOLEAN NOT NULL DEFAULT TRUE,
    completion_percent INTEGER NOT NULL DEFAULT 0 CHECK (completion_percent BETWEEN 0 AND 100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_deliverables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    milestone_id BIGINT REFERENCES public.project_milestones(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    file_path TEXT,
    status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted','under_review','changes_requested','resubmitted','approved')),
    submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    review_notes TEXT,
    client_visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.project_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
    actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    actor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    description TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_projects_client_id ON public.projects(client_id);
CREATE INDEX IF NOT EXISTS idx_projects_status ON public.projects(status);
CREATE INDEX IF NOT EXISTS idx_projects_updated_at ON public.projects(updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_project_members_project ON public.project_members(project_id);
CREATE INDEX IF NOT EXISTS idx_project_milestones_project ON public.project_milestones(project_id);
CREATE INDEX IF NOT EXISTS idx_project_tasks_project ON public.project_tasks(project_id);
CREATE INDEX IF NOT EXISTS idx_project_tasks_milestone ON public.project_tasks(milestone_id);
CREATE INDEX IF NOT EXISTS idx_project_deliverables_project ON public.project_deliverables(project_id);
CREATE INDEX IF NOT EXISTS idx_project_activity_project ON public.project_activity(project_id, created_at DESC);

DROP TRIGGER IF EXISTS trg_projects_updated_at ON public.projects;
CREATE TRIGGER trg_projects_updated_at BEFORE UPDATE ON public.projects FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_project_milestones_updated_at ON public.project_milestones;
CREATE TRIGGER trg_project_milestones_updated_at BEFORE UPDATE ON public.project_milestones FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_project_tasks_updated_at ON public.project_tasks;
CREATE TRIGGER trg_project_tasks_updated_at BEFORE UPDATE ON public.project_tasks FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_project_deliverables_updated_at ON public.project_deliverables;
CREATE TRIGGER trg_project_deliverables_updated_at BEFORE UPDATE ON public.project_deliverables FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_deliverables ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.project_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Project service role access" ON public.projects;
CREATE POLICY "Project service role access" ON public.projects FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Project members service role access" ON public.project_members;
CREATE POLICY "Project members service role access" ON public.project_members FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Project milestones service role access" ON public.project_milestones;
CREATE POLICY "Project milestones service role access" ON public.project_milestones FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Project tasks service role access" ON public.project_tasks;
CREATE POLICY "Project tasks service role access" ON public.project_tasks FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Project deliverables service role access" ON public.project_deliverables;
CREATE POLICY "Project deliverables service role access" ON public.project_deliverables FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Project activity service role access" ON public.project_activity;
CREATE POLICY "Project activity service role access" ON public.project_activity FOR ALL TO service_role USING (true) WITH CHECK (true);
