-- ==============================================================================
-- THINKATIC MIGRATION: ENHANCE MEETINGS AND MULTI-TENANT RECIPIENTS
-- Connects Admin Meetings with BPO Partners, Clients, and Multi-Tenant Recipient Targeting
-- ==============================================================================

-- 1. Ensure 'meetings' and 'partner_meetings' modules are enabled in settings
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('meetings', TRUE), ('partner_meetings', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. Relax legacy NOT NULL constraints on public.meetings to support General & BPO meetings
ALTER TABLE public.meetings ALTER COLUMN client_id DROP NOT NULL;
ALTER TABLE public.meetings ALTER COLUMN project_id DROP NOT NULL;

-- 3. Add additive columns to public.meetings for link, encrypted password, audience scope, and notes
ALTER TABLE public.meetings ADD COLUMN IF NOT EXISTS meeting_link TEXT;
ALTER TABLE public.meetings ADD COLUMN IF NOT EXISTS meeting_password_encrypted TEXT;
ALTER TABLE public.meetings ADD COLUMN IF NOT EXISTS audience_type TEXT NOT NULL DEFAULT 'client';
ALTER TABLE public.meetings ADD COLUMN IF NOT EXISTS notes TEXT;

-- 4. Update meeting_type check constraint to accommodate all required enterprise meeting types
ALTER TABLE public.meetings DROP CONSTRAINT IF EXISTS meetings_meeting_type_check;
ALTER TABLE public.meetings ADD CONSTRAINT meetings_meeting_type_check CHECK (
  meeting_type IN (
    'project_meeting',
    'client_meeting',
    'bpo_partner_meeting',
    'operations_meeting',
    'training',
    'review',
    'general_meeting',
    'requirement_discussion',
    'demo',
    'uat',
    'planning',
    'support',
    'other'
  )
);

-- 5. Create public.meeting_recipients for explicit recipient targeting and delivery auditing
CREATE TABLE IF NOT EXISTS public.meeting_recipients (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  recipient_type TEXT NOT NULL CHECK (recipient_type IN ('CLIENT', 'BPO_PARTNER', 'ALL_CLIENTS', 'ALL_BPO_PARTNERS', 'EVERYONE')),
  recipient_id TEXT, -- Profile UUID or Partner UUID, null if broadcast (ALL_*)
  delivery_status TEXT NOT NULL DEFAULT 'delivered' CHECK (delivery_status IN ('pending', 'delivered', 'failed', 'viewed')),
  viewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Indexes for high-speed recipient authorization lookups
CREATE INDEX IF NOT EXISTS idx_meetings_audience ON public.meetings(audience_type, starts_at);
CREATE INDEX IF NOT EXISTS idx_meeting_recipients_meeting ON public.meeting_recipients(meeting_id);
CREATE INDEX IF NOT EXISTS idx_meeting_recipients_target ON public.meeting_recipients(recipient_type, recipient_id);

-- 7. Enable RLS and setup policies
ALTER TABLE public.meeting_recipients ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  DROP POLICY IF EXISTS "meeting_recipients service role access" ON public.meeting_recipients;
  CREATE POLICY "meeting_recipients service role access" ON public.meeting_recipients FOR ALL TO service_role USING (true) WITH CHECK (true);
EXCEPTION WHEN OTHERS THEN NULL;
END $$;
