-- ==============================================================================
-- Migration: 20260918000000_bpo_phase8_integrations.sql
-- Description: Phase 8 - Dialer + CRM + Advanced Integrations
--              Normalized Integrations, Encrypted Credentials, Sync Jobs,
--              CRM Leads/Contacts, Call Activities, and Webhook Deduplication.
-- ==============================================================================

-- 1. Enable bpo_integrations module flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_integrations', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. Integrations Catalog
CREATE TABLE IF NOT EXISTS public.bpo_integrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_code TEXT UNIQUE NOT NULL, -- THK-INT-XXXXX
  tenant_type TEXT NOT NULL DEFAULT 'client' CHECK (tenant_type IN ('client', 'partner', 'admin')),
  client_id UUID REFERENCES public.bpo_clients(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  provider_type TEXT NOT NULL CHECK (provider_type IN ('CRM', 'DIALER', 'WEBHOOK')),
  provider_name TEXT NOT NULL CHECK (provider_name IN (
    'salesforce', 'hubspot', 'zoho', 'custom_rest_crm',
    'vicidial', 'genesys', 'twilio', 'custom_rest_dialer',
    'generic_webhook'
  )),
  display_name TEXT NOT NULL CHECK (char_length(display_name) BETWEEN 2 AND 100),
  description TEXT,
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'paused', 'error', 'disconnected')),
  health_status TEXT NOT NULL DEFAULT 'unknown'
    CHECK (health_status IN ('healthy', 'degraded', 'down', 'unknown')),
  auth_type TEXT NOT NULL DEFAULT 'api_key'
    CHECK (auth_type IN ('api_key', 'oauth2', 'basic_auth', 'webhook_secret', 'token')),
  base_url TEXT,
  webhook_url TEXT,
  webhook_secret_hash TEXT,
  sync_interval_minutes INTEGER NOT NULL DEFAULT 15 CHECK (sync_interval_minutes >= 1),
  auto_sync_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  last_synced_at TIMESTAMPTZ,
  last_health_check_at TIMESTAMPTZ,
  last_error TEXT,
  config JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_by_user_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_int_client ON public.bpo_integrations(client_id);
CREATE INDEX IF NOT EXISTS idx_bpo_int_partner ON public.bpo_integrations(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_int_provider_type ON public.bpo_integrations(provider_type);
CREATE INDEX IF NOT EXISTS idx_bpo_int_status ON public.bpo_integrations(status);
CREATE INDEX IF NOT EXISTS idx_bpo_int_code ON public.bpo_integrations(integration_code);

ALTER TABLE public.bpo_integrations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_integrations service role access" ON public.bpo_integrations;
CREATE POLICY "bpo_integrations service role access" ON public.bpo_integrations
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. Encrypted Integration Credentials (AES-256-GCM)
CREATE TABLE IF NOT EXISTS public.bpo_integration_credentials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_id BIGINT UNIQUE NOT NULL REFERENCES public.bpo_integrations(id) ON DELETE CASCADE,
  encrypted_data TEXT NOT NULL, -- AES-256-GCM ciphertext hex
  iv TEXT NOT NULL,             -- 12-byte initialization vector hex
  auth_tag TEXT NOT NULL,       -- 16-byte authentication tag hex
  key_masked TEXT NOT NULL,     -- Masked representation e.g. ••••••••1234
  token_type TEXT DEFAULT 'Bearer',
  expires_at TIMESTAMPTZ,
  refresh_expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_int_cred_int ON public.bpo_integration_credentials(integration_id);

ALTER TABLE public.bpo_integration_credentials ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_integration_credentials service role access" ON public.bpo_integration_credentials;
CREATE POLICY "bpo_integration_credentials service role access" ON public.bpo_integration_credentials
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. Integration Sync Jobs
CREATE TABLE IF NOT EXISTS public.bpo_integration_sync_jobs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_code TEXT UNIQUE NOT NULL, -- THK-SNC-XXXXX
  integration_id BIGINT NOT NULL REFERENCES public.bpo_integrations(id) ON DELETE CASCADE,
  sync_type TEXT NOT NULL DEFAULT 'incremental' CHECK (sync_type IN ('initial', 'incremental', 'manual', 'webhook_triggered')),
  status TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('pending', 'running', 'completed', 'failed', 'cancelled')),
  records_processed INTEGER NOT NULL DEFAULT 0 CHECK (records_processed >= 0),
  records_succeeded INTEGER NOT NULL DEFAULT 0 CHECK (records_succeeded >= 0),
  records_failed INTEGER NOT NULL DEFAULT 0 CHECK (records_failed >= 0),
  cursor_checkpoint TEXT,
  retry_count INTEGER NOT NULL DEFAULT 0 CHECK (retry_count >= 0),
  error_details TEXT,
  started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_sync_jobs_int ON public.bpo_integration_sync_jobs(integration_id);
CREATE INDEX IF NOT EXISTS idx_bpo_sync_jobs_status ON public.bpo_integration_sync_jobs(status);
CREATE INDEX IF NOT EXISTS idx_bpo_sync_jobs_created ON public.bpo_integration_sync_jobs(created_at DESC);

ALTER TABLE public.bpo_integration_sync_jobs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_integration_sync_jobs service role access" ON public.bpo_integration_sync_jobs;
CREATE POLICY "bpo_integration_sync_jobs service role access" ON public.bpo_integration_sync_jobs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. CRM Leads & Customer Records
CREATE TABLE IF NOT EXISTS public.bpo_crm_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lead_code TEXT UNIQUE NOT NULL, -- THK-LED-XXXXX
  integration_id BIGINT NOT NULL REFERENCES public.bpo_integrations(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES public.bpo_clients(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  external_lead_id TEXT NOT NULL,
  first_name TEXT NOT NULL DEFAULT '',
  last_name TEXT NOT NULL DEFAULT '',
  email TEXT,
  phone TEXT,
  company TEXT,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'contacted', 'qualified', 'converted', 'lost', 'dnc')),
  disposition TEXT,
  assigned_agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  custom_fields JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_synced_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_crm_lead_external UNIQUE (integration_id, external_lead_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_crm_leads_client ON public.bpo_crm_leads(client_id);
CREATE INDEX IF NOT EXISTS idx_bpo_crm_leads_project ON public.bpo_crm_leads(project_id);
CREATE INDEX IF NOT EXISTS idx_bpo_crm_leads_status ON public.bpo_crm_leads(status);
CREATE INDEX IF NOT EXISTS idx_bpo_crm_leads_ext ON public.bpo_crm_leads(external_lead_id);

ALTER TABLE public.bpo_crm_leads ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_crm_leads service role access" ON public.bpo_crm_leads;
CREATE POLICY "bpo_crm_leads service role access" ON public.bpo_crm_leads
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 6. Call Activities (Telephony / Dialer Events)
CREATE TABLE IF NOT EXISTS public.bpo_call_activities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  call_code TEXT UNIQUE NOT NULL, -- THK-CAL-XXXXX
  integration_id BIGINT NOT NULL REFERENCES public.bpo_integrations(id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  client_id UUID REFERENCES public.bpo_clients(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  lead_id BIGINT REFERENCES public.bpo_crm_leads(id) ON DELETE SET NULL,
  external_call_id TEXT NOT NULL,
  call_direction TEXT NOT NULL DEFAULT 'inbound' CHECK (call_direction IN ('inbound', 'outbound')),
  start_time TIMESTAMPTZ NOT NULL,
  end_time TIMESTAMPTZ,
  duration_seconds INTEGER NOT NULL DEFAULT 0 CHECK (duration_seconds >= 0),
  call_status TEXT NOT NULL DEFAULT 'completed'
    CHECK (call_status IN ('completed', 'missed', 'busy', 'failed', 'dropped', 'in_progress', 'transferred')),
  disposition TEXT,
  transfer_status TEXT DEFAULT 'none',
  recording_reference TEXT,
  recording_duration_seconds INTEGER DEFAULT 0,
  caller_number TEXT,
  recipient_number TEXT,
  qa_score NUMERIC(5,2),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_call_activity_external UNIQUE (integration_id, external_call_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_calls_client ON public.bpo_call_activities(client_id);
CREATE INDEX IF NOT EXISTS idx_bpo_calls_partner ON public.bpo_call_activities(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_calls_project ON public.bpo_call_activities(project_id);
CREATE INDEX IF NOT EXISTS idx_bpo_calls_agent ON public.bpo_call_activities(agent_id);
CREATE INDEX IF NOT EXISTS idx_bpo_calls_status ON public.bpo_call_activities(call_status);
CREATE INDEX IF NOT EXISTS idx_bpo_calls_time ON public.bpo_call_activities(start_time DESC);

ALTER TABLE public.bpo_call_activities ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_call_activities service role access" ON public.bpo_call_activities;
CREATE POLICY "bpo_call_activities service role access" ON public.bpo_call_activities
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 7. Webhook Reception & Deduplication Ledger
CREATE TABLE IF NOT EXISTS public.bpo_integration_webhooks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  integration_id BIGINT NOT NULL REFERENCES public.bpo_integrations(id) ON DELETE CASCADE,
  external_event_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  signature_verified BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'processed' CHECK (status IN ('received', 'processed', 'duplicate', 'failed', 'rejected')),
  error_message TEXT,
  received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processed_at TIMESTAMPTZ,
  CONSTRAINT uq_webhook_event UNIQUE (integration_id, external_event_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_webhooks_int ON public.bpo_integration_webhooks(integration_id);
CREATE INDEX IF NOT EXISTS idx_bpo_webhooks_ext ON public.bpo_integration_webhooks(external_event_id);
CREATE INDEX IF NOT EXISTS idx_bpo_webhooks_status ON public.bpo_integration_webhooks(status);

ALTER TABLE public.bpo_integration_webhooks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_integration_webhooks service role access" ON public.bpo_integration_webhooks;
CREATE POLICY "bpo_integration_webhooks service role access" ON public.bpo_integration_webhooks
  FOR ALL TO service_role USING (true) WITH CHECK (true);
