-- ==============================================================================
-- Migration: 20260913000000_bpo_phase3_agents_training.sql
-- Description: Phase 3 - Agent Management, Training Modules, Assessments,
--              Certifications, and Agent Documents for Thinkatic BPO Delivery
-- ==============================================================================

-- 1. Extend bpo_agents with Phase 3 attributes & lifecycle states
ALTER TABLE public.bpo_agents
  ADD COLUMN IF NOT EXISTS agent_code TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS designation TEXT DEFAULT 'Frontline Agent',
  ADD COLUMN IF NOT EXISTS department TEXT DEFAULT 'Customer Operations',
  ADD COLUMN IF NOT EXISTS experience_years NUMERIC(4,1) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS languages JSONB NOT NULL DEFAULT '["English"]'::jsonb,
  ADD COLUMN IF NOT EXISTS skills JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS shift_preference TEXT DEFAULT 'US Day',
  ADD COLUMN IF NOT EXISTS onboarding_status TEXT NOT NULL DEFAULT 'submitted'
    CHECK (onboarding_status IN ('draft', 'submitted', 'pending_verification', 'verified', 'action_required', 'rejected')),
  ADD COLUMN IF NOT EXISTS training_status TEXT NOT NULL DEFAULT 'not_started'
    CHECK (training_status IN ('not_started', 'in_progress', 'completed', 'certified', 'failed')),
  ADD COLUMN IF NOT EXISTS certification_status TEXT NOT NULL DEFAULT 'none'
    CHECK (certification_status IN ('none', 'pending', 'active', 'expiring', 'expired', 'revoked')),
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB NOT NULL DEFAULT '{}'::jsonb;

-- Update status check constraint on bpo_agents to include Phase 3 lifecycle states
ALTER TABLE public.bpo_agents DROP CONSTRAINT IF EXISTS bpo_agents_status_check;
ALTER TABLE public.bpo_agents ADD CONSTRAINT bpo_agents_status_check
  CHECK (status IN ('draft', 'pending_verification', 'active', 'training', 'on_hold', 'inactive', 'suspended', 'terminated', 'on_leave'));

CREATE INDEX IF NOT EXISTS idx_bpo_agents_code ON public.bpo_agents(agent_code);
CREATE INDEX IF NOT EXISTS idx_bpo_agents_onboarding_status ON public.bpo_agents(onboarding_status);
CREATE INDEX IF NOT EXISTS idx_bpo_agents_training_status ON public.bpo_agents(training_status);
CREATE INDEX IF NOT EXISTS idx_bpo_agents_cert_status ON public.bpo_agents(certification_status);

-- 2. Agent Compliance Documents
CREATE TABLE IF NOT EXISTS public.bpo_agent_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL CHECK (document_type IN ('id_proof', 'address_proof', 'educational_cert', 'employment_contract', 'nda', 'training_cert', 'other')),
  document_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_size BIGINT,
  mime_type TEXT NOT NULL,
  verification_status TEXT NOT NULL DEFAULT 'pending' CHECK (verification_status IN ('pending', 'verified', 'rejected')),
  rejection_notes TEXT,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  verified_at TIMESTAMPTZ,
  verified_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_bpo_agent_docs_agent ON public.bpo_agent_documents(agent_id);
CREATE INDEX IF NOT EXISTS idx_bpo_agent_docs_partner ON public.bpo_agent_documents(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_agent_docs_status ON public.bpo_agent_documents(verification_status);

ALTER TABLE public.bpo_agent_documents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_agent_documents service role access" ON public.bpo_agent_documents;
CREATE POLICY "bpo_agent_documents service role access" ON public.bpo_agent_documents
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. Extend bpo_training_programs
ALTER TABLE public.bpo_training_programs
  ADD COLUMN IF NOT EXISTS training_code TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT 'Process Training',
  ADD COLUMN IF NOT EXISTS duration_hours INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN IF NOT EXISTS passing_score NUMERIC(5,2) NOT NULL DEFAULT 80.00,
  ADD COLUMN IF NOT EXISTS is_mandatory BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS is_global BOOLEAN NOT NULL DEFAULT TRUE;

CREATE INDEX IF NOT EXISTS idx_bpo_training_programs_code ON public.bpo_training_programs(training_code);

-- 4. Training Modules
CREATE TABLE IF NOT EXISTS public.bpo_training_modules (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES public.bpo_training_programs(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  order_index INTEGER NOT NULL DEFAULT 1,
  duration_minutes INTEGER NOT NULL DEFAULT 60,
  content TEXT,
  is_mandatory BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_training_modules_program ON public.bpo_training_modules(program_id);

ALTER TABLE public.bpo_training_modules ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_training_modules service role access" ON public.bpo_training_modules;
CREATE POLICY "bpo_training_modules service role access" ON public.bpo_training_modules
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. Agent Module Completion Progress
CREATE TABLE IF NOT EXISTS public.bpo_agent_module_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assignment_id BIGINT NOT NULL REFERENCES public.bpo_training_assignments(id) ON DELETE CASCADE,
  module_id BIGINT NOT NULL REFERENCES public.bpo_training_modules(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  completed BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at TIMESTAMPTZ,
  score NUMERIC(5,2),
  UNIQUE (assignment_id, module_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_module_progress_assignment ON public.bpo_agent_module_progress(assignment_id);
CREATE INDEX IF NOT EXISTS idx_bpo_module_progress_agent ON public.bpo_agent_module_progress(agent_id);

ALTER TABLE public.bpo_agent_module_progress ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_agent_module_progress service role access" ON public.bpo_agent_module_progress;
CREATE POLICY "bpo_agent_module_progress service role access" ON public.bpo_agent_module_progress
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 6. Extend bpo_agent_certifications
ALTER TABLE public.bpo_agent_certifications
  ADD COLUMN IF NOT EXISTS certificate_code TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS training_program_id BIGINT REFERENCES public.bpo_training_programs(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS certification_name TEXT DEFAULT 'Thinkatic Certified Delivery Specialist',
  ADD COLUMN IF NOT EXISTS issuing_authority TEXT NOT NULL DEFAULT 'Thinkatic Global Operations',
  ADD COLUMN IF NOT EXISTS revoked_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS revocation_reason TEXT;

-- Update status check constraint on bpo_agent_certifications
ALTER TABLE public.bpo_agent_certifications DROP CONSTRAINT IF EXISTS bpo_agent_certifications_status_check;
ALTER TABLE public.bpo_agent_certifications ADD CONSTRAINT bpo_agent_certifications_status_check
  CHECK (status IN ('pending', 'certified', 'active', 'expiring', 'expired', 'retraining_required', 'revoked'));

CREATE INDEX IF NOT EXISTS idx_bpo_agent_certs_code ON public.bpo_agent_certifications(certificate_code);
CREATE INDEX IF NOT EXISTS idx_bpo_agent_certs_status ON public.bpo_agent_certifications(status);
