-- ==============================================================================
-- Migration: 20260921000000_create_bpo_centre_verification.sql
-- Description: Thinkatic BPO Partner Office / Centre Verification module.
--              Stores structured office attributes, address, categories of
--              photo evidence, live browser-recorded walkthrough video metadata,
--              Admin reviews, approvals/rejections, and resubmission audit history.
--              NO AI: Purely human evidence for Thinkatic Admin/Operations review.
--              STORAGE: Photos and video binaries stored in private storage;
--                       PostgreSQL stores structured metadata and audit records.
-- ==============================================================================

-- 1. Enable module setting flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_centre_verification', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. BPO Centre Verification Table
CREATE TABLE IF NOT EXISTS public.bpo_centre_verification (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE SET NULL,
  application_id BIGINT REFERENCES public.bpo_partner_applications(id) ON DELETE SET NULL,
  centre_id TEXT, -- Populated if Centre ID already issued
  applicant_user_id TEXT NOT NULL,

  -- Office / Centre Attributes
  office_name TEXT NOT NULL,
  address_line_1 TEXT NOT NULL,
  address_line_2 TEXT,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  country TEXT NOT NULL DEFAULT 'India',
  postal_code TEXT NOT NULL,
  landmark TEXT,
  contact_number TEXT NOT NULL,
  centre_type TEXT NOT NULL DEFAULT 'Dedicated BPO Facility', -- e.g. Dedicated BPO Facility, Corporate Branch, Technology Park, Co-working Floor
  ownership_type TEXT NOT NULL DEFAULT 'Commercial Lease', -- e.g. Owned, Commercial Lease, Rented, Operational Agreement
  operating_since TEXT NOT NULL,
  total_area_sqft NUMERIC(10,2),
  number_of_floors INTEGER DEFAULT 1,

  -- Verification Lifecycle Status
  status TEXT NOT NULL DEFAULT 'NOT_STARTED'
    CHECK (status IN (
      'NOT_STARTED',
      'IN_PROGRESS',
      'SUBMITTED',
      'UNDER_REVIEW',
      'APPROVED',
      'REJECTED',
      'RESUBMISSION_REQUIRED'
    )),

  -- Timestamps & Submissions
  submitted_at TIMESTAMPTZ,
  submission_count INTEGER NOT NULL DEFAULT 0,

  -- Human Admin Review
  reviewed_at TIMESTAMPTZ,
  reviewed_by_admin_id BIGINT,
  reviewed_by_admin_name TEXT,
  rejection_reason TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_user ON public.bpo_centre_verification(applicant_user_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_partner ON public.bpo_centre_verification(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_app ON public.bpo_centre_verification(application_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_status ON public.bpo_centre_verification(status);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_centre ON public.bpo_centre_verification(centre_id);

-- 3. BPO Centre Media Evidence Table (Categorized Photos & Live Video)
CREATE TABLE IF NOT EXISTS public.bpo_centre_media (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verification_id BIGINT NOT NULL REFERENCES public.bpo_centre_verification(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE SET NULL,
  applicant_user_id TEXT NOT NULL,
  centre_id TEXT,

  media_type TEXT NOT NULL CHECK (media_type IN ('photo', 'video')),
  category TEXT NOT NULL, -- reception_entrance, workstation_area, operations_area, management_area, infrastructure_equipment, network_setup, power_backup, security_access, live_walkthrough
  storage_key TEXT NOT NULL, -- relative private path: bpo/centre-verification/{partnerId}/{verificationId}/...
  original_file_name TEXT NOT NULL,
  mime_type TEXT NOT NULL,
  file_size INTEGER NOT NULL,
  duration_seconds INTEGER, -- for video
  uploaded_by TEXT NOT NULL,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'archived', 'superseded'))
);

CREATE INDEX IF NOT EXISTS idx_bpo_centre_media_verif ON public.bpo_centre_media(verification_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_media_type ON public.bpo_centre_media(media_type);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_media_cat ON public.bpo_centre_media(category);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_media_user ON public.bpo_centre_media(applicant_user_id);

-- 4. BPO Centre Verification History (Preserves previous submissions & audit transitions)
CREATE TABLE IF NOT EXISTS public.bpo_centre_verification_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  verification_id BIGINT NOT NULL REFERENCES public.bpo_centre_verification(id) ON DELETE CASCADE,
  submission_round INTEGER NOT NULL DEFAULT 1,
  action TEXT NOT NULL, -- created, details_updated, photo_uploaded, video_uploaded, submitted, under_review, approved, rejected, resubmitted
  from_status TEXT,
  to_status TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  actor_role TEXT NOT NULL DEFAULT 'partner', -- partner, admin, system
  actor_name TEXT,
  notes TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_centre_verif_hist_verif ON public.bpo_centre_verification_history(verification_id);

-- 5. Row Level Security (RLS)
ALTER TABLE public.bpo_centre_verification ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_centre_media ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_centre_verification_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "bpo_centre_verification service role access" ON public.bpo_centre_verification;
CREATE POLICY "bpo_centre_verification service role access" ON public.bpo_centre_verification
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "bpo_centre_media service role access" ON public.bpo_centre_media;
CREATE POLICY "bpo_centre_media service role access" ON public.bpo_centre_media
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "bpo_centre_verification_history service role access" ON public.bpo_centre_verification_history;
CREATE POLICY "bpo_centre_verification_history service role access" ON public.bpo_centre_verification_history
  FOR ALL TO service_role USING (true) WITH CHECK (true);
