-- Additive partner operational modules. No client financial data is copied.
INSERT INTO public.module_settings(module_key, enabled) VALUES
 ('partner_documents', TRUE), ('partner_meetings', TRUE), ('partner_training', TRUE),
 ('partner_productivity', TRUE), ('partner_quality', TRUE), ('partner_payouts', TRUE), ('partner_reports', TRUE)
ON CONFLICT (module_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.bpo_partner_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  document_id BIGINT NOT NULL REFERENCES public.documents(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  partner_project_id BIGINT REFERENCES public.bpo_partner_projects(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(document_id, partner_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_partner_meetings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  partner_project_id BIGINT REFERENCES public.bpo_partner_projects(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(meeting_id, partner_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_partner_meeting_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  meeting_id BIGINT NOT NULL REFERENCES public.meetings(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rsvp_status TEXT NOT NULL DEFAULT 'pending' CHECK (rsvp_status IN ('pending','accepted','declined','tentative')),
  responded_at TIMESTAMPTZ,
  UNIQUE(meeting_id, user_id)
);

ALTER TABLE public.meeting_notes ADD COLUMN IF NOT EXISTS partner_visible BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS public.bpo_training_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  partner_project_id BIGINT REFERENCES public.bpo_partner_projects(id) ON DELETE SET NULL,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 200),
  description TEXT,
  starts_at TIMESTAMPTZ,
  ends_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','scheduled','in_progress','completed','failed')),
  completion_percent INTEGER NOT NULL DEFAULT 0 CHECK (completion_percent BETWEEN 0 AND 100),
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bpo_training_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id BIGINT NOT NULL REFERENCES public.bpo_training_programs(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_started' CHECK (status IN ('not_started','scheduled','in_progress','completed','failed')),
  completion_percent INTEGER NOT NULL DEFAULT 0 CHECK (completion_percent BETWEEN 0 AND 100),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(program_id, agent_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_quality_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_project_id BIGINT REFERENCES public.bpo_partner_projects(id) ON DELETE SET NULL,
  score NUMERIC(5,2) NOT NULL CHECK (score >= 0 AND score <= 100),
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft','submitted','reviewed','disputed')),
  evaluation_date DATE NOT NULL DEFAULT CURRENT_DATE,
  partner_visible BOOLEAN NOT NULL DEFAULT TRUE,
  internal_notes TEXT,
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bpo_payout_statements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  statement_number TEXT NOT NULL UNIQUE,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  payable_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (payable_amount >= 0),
  approved_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (approved_amount >= 0),
  paid_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
  pending_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (pending_amount >= 0),
  payout_date DATE,
  reference TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','processing','paid','rejected','cancelled')),
  internal_notes TEXT,
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT payout_statement_period_order CHECK (period_end >= period_start)
);

CREATE INDEX IF NOT EXISTS idx_bpo_partner_documents_partner ON public.bpo_partner_documents(partner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_meetings_partner ON public.bpo_partner_meetings(partner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_meeting_users_user ON public.bpo_partner_meeting_users(user_id, meeting_id);
CREATE INDEX IF NOT EXISTS idx_bpo_training_programs_partner ON public.bpo_training_programs(partner_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_bpo_training_assignments_agent ON public.bpo_training_assignments(agent_id, program_id);
CREATE INDEX IF NOT EXISTS idx_bpo_quality_partner ON public.bpo_quality_evaluations(partner_id, evaluation_date DESC);
CREATE INDEX IF NOT EXISTS idx_bpo_payout_partner ON public.bpo_payout_statements(partner_id, period_end DESC);

DROP TRIGGER IF EXISTS trg_bpo_training_programs_updated_at ON public.bpo_training_programs;
CREATE TRIGGER trg_bpo_training_programs_updated_at BEFORE UPDATE ON public.bpo_training_programs FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_bpo_payout_statements_updated_at ON public.bpo_payout_statements;
CREATE TRIGGER trg_bpo_payout_statements_updated_at BEFORE UPDATE ON public.bpo_payout_statements FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.bpo_partner_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_partner_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_partner_meeting_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_training_programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_training_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_quality_evaluations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_payout_statements ENABLE ROW LEVEL SECURITY;

DO $$ DECLARE table_name TEXT; BEGIN
  FOREACH table_name IN ARRAY ARRAY['bpo_partner_documents','bpo_partner_meetings','bpo_partner_meeting_users','bpo_training_programs','bpo_training_assignments','bpo_quality_evaluations','bpo_payout_statements'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', table_name || ' service role access', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', table_name || ' service role access', table_name);
  END LOOP;
END $$;
