-- ============================================================================
-- Thinkatic BPO Global Delivery Platform — Missing System Delta Schema
-- Based on Thinkatic Missing Features PRD + System Blueprint (18 September 2026)
-- ============================================================================

-- Enable new BPO system module flags in module_settings
INSERT INTO public.module_settings (module_key, enabled)
VALUES 
  ('bpo_partner_applications', TRUE),
  ('bpo_project_marketplace', TRUE),
  ('bpo_certification_engine', TRUE),
  ('bpo_adaptive_production', TRUE),
  ('bpo_capacity_matching', TRUE),
  ('bpo_client_portal', TRUE),
  ('bpo_ai_qa', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 1. BPO Partner Applications (Multi-step onboarding wizard persistence)
CREATE TABLE IF NOT EXISTS public.bpo_partner_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_number TEXT NOT NULL UNIQUE,
  applicant_user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'submitted', 'under_review', 'documents_required', 'infrastructure_check', 'management_check', 'trial_assessment', 'approved', 'rejected', 'withdrawn', 'suspended')),
  current_stage TEXT NOT NULL DEFAULT 'registration' CHECK (current_stage IN ('registration', 'documents', 'thinkatic_verification', 'infrastructure', 'management', 'trial_assessment', 'approved', 'centre_id_generated')),
  company_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  centre_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  infrastructure_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  process_experience JSONB NOT NULL DEFAULT '[]'::jsonb,
  verification_checks JSONB NOT NULL DEFAULT '{}'::jsonb,
  missing_information JSONB NOT NULL DEFAULT '[]'::jsonb,
  rejection_reason TEXT,
  submitted_at TIMESTAMPTZ,
  reviewed_at TIMESTAMPTZ,
  reviewed_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 2. BPO Application Documents
CREATE TABLE IF NOT EXISTS public.bpo_application_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES public.bpo_partner_applications(id) ON DELETE CASCADE,
  document_id BIGINT REFERENCES public.documents(id) ON DELETE CASCADE,
  document_type TEXT NOT NULL,
  file_name TEXT,
  file_url TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'verified', 'rejected', 'expired')),
  reviewer_notes TEXT,
  verified_at TIMESTAMPTZ,
  verified_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. BPO Application Events (Audit trail for timeline progression)
CREATE TABLE IF NOT EXISTS public.bpo_application_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES public.bpo_partner_applications(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  stage TEXT,
  note TEXT,
  actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 4. BPO Project Applications (Partner applying for available projects)
CREATE TABLE IF NOT EXISTS public.bpo_project_applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_number TEXT NOT NULL UNIQUE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  available_seats INTEGER NOT NULL DEFAULT 0 CHECK (available_seats >= 0),
  experienced_agents INTEGER NOT NULL DEFAULT 0 CHECK (experienced_agents >= 0),
  us_experience BOOLEAN NOT NULL DEFAULT FALSE,
  uk_experience BOOLEAN NOT NULL DEFAULT FALSE,
  available_start_date DATE,
  current_projects INTEGER NOT NULL DEFAULT 0,
  infrastructure_confirmed BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft', 'submitted', 'under_review', 'eligibility_check', 'assessment', 'more_info_required', 'approved', 'rejected', 'allocated', 'accepted', 'withdrawn')),
  reviewer_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  reviewer_notes TEXT,
  allocated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(partner_id, project_id)
);

-- 5. BPO Project Application Events
CREATE TABLE IF NOT EXISTS public.bpo_project_application_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT NOT NULL REFERENCES public.bpo_project_applications(id) ON DELETE CASCADE,
  from_status TEXT,
  to_status TEXT NOT NULL,
  note TEXT,
  actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 6. Project Metric Definitions (Configurable metrics per project type)
CREATE TABLE IF NOT EXISTS public.bpo_project_metric_definitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  metric_key TEXT NOT NULL,
  label TEXT NOT NULL,
  unit TEXT,
  target NUMERIC,
  required BOOLEAN NOT NULL DEFAULT FALSE,
  UNIQUE(project_id, metric_key)
);

-- 7. Production Daily (Adaptive production reporting)
CREATE TABLE IF NOT EXISTS public.bpo_production_daily (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  production_date DATE NOT NULL,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'dialer', 'crm', 'csv_import')),
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  approved_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(project_id, agent_id, production_date)
);

-- 8. Certification Tests (Configurable assessment engine)
CREATE TABLE IF NOT EXISTS public.bpo_certification_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  total_questions INTEGER NOT NULL DEFAULT 30,
  passing_score NUMERIC(5,2) NOT NULL DEFAULT 80.00,
  time_limit_minutes INTEGER DEFAULT 45,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'draft', 'archived')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 9. Certification Questions (30-question bank)
CREATE TABLE IF NOT EXISTS public.bpo_certification_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_id BIGINT NOT NULL REFERENCES public.bpo_certification_tests(id) ON DELETE CASCADE,
  question_text TEXT NOT NULL,
  options JSONB NOT NULL DEFAULT '[]'::jsonb,
  correct_option_index INTEGER NOT NULL,
  explanation TEXT,
  module_name TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. Agent Certification Attempts & Records
CREATE TABLE IF NOT EXISTS public.bpo_certification_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  test_id BIGINT NOT NULL REFERENCES public.bpo_certification_tests(id) ON DELETE CASCADE,
  score NUMERIC(5,2) NOT NULL,
  passed BOOLEAN NOT NULL,
  answers JSONB NOT NULL DEFAULT '{}'::jsonb,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bpo_agent_certifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'certified', 'retraining_required', 'expired')),
  score NUMERIC(5,2),
  certified_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  UNIQUE(agent_id, project_id)
);

-- 11. Capacity Snapshots (For geographic marketplace & matching engine)
CREATE TABLE IF NOT EXISTS public.bpo_capacity_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  city TEXT NOT NULL DEFAULT 'Pune',
  snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
  available_seats INTEGER NOT NULL DEFAULT 0,
  languages JSONB NOT NULL DEFAULT '["English", "Hindi"]'::jsonb,
  processes JSONB NOT NULL DEFAULT '["outbound", "customer_support"]'::jsonb,
  shifts JSONB NOT NULL DEFAULT '["US Shift", "UK Shift"]'::jsonb,
  infrastructure JSONB NOT NULL DEFAULT '{}'::jsonb,
  qa_score NUMERIC(5,2),
  attendance_score NUMERIC(5,2),
  compliance_score NUMERIC(5,2),
  UNIQUE(partner_id, centre_id, snapshot_date)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_bpo_partner_applications_applicant ON public.bpo_partner_applications(applicant_user_id);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_applications_status ON public.bpo_partner_applications(status);
CREATE INDEX IF NOT EXISTS idx_bpo_project_applications_partner ON public.bpo_project_applications(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_project_applications_project ON public.bpo_project_applications(project_id);
CREATE INDEX IF NOT EXISTS idx_bpo_production_daily_project_date ON public.bpo_production_daily(project_id, production_date);
CREATE INDEX IF NOT EXISTS idx_bpo_capacity_snapshots_city ON public.bpo_capacity_snapshots(city, snapshot_date);
