-- ==============================================================================
-- Migration: 20260915000000_bpo_phase5_client_portal.sql
-- Description: Phase 5 - Client Portal & Client Reporting Foundation
--              Client entity (THK-CLI-XXXXX), Client User RBAC,
--              Client-Project associations, and tenant isolation policies.
-- ==============================================================================

-- 1. BPO Clients Registry (Enterprise Client Accounts)
CREATE TABLE IF NOT EXISTS public.bpo_clients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_code TEXT NOT NULL UNIQUE,
  company_name TEXT NOT NULL CHECK (char_length(company_name) BETWEEN 2 AND 250),
  legal_name TEXT,
  country TEXT NOT NULL DEFAULT 'United States',
  industry TEXT NOT NULL DEFAULT 'General',
  primary_contact TEXT NOT NULL,
  contact_email TEXT NOT NULL,
  contact_phone TEXT,
  account_status TEXT NOT NULL DEFAULT 'active'
    CHECK (account_status IN ('active', 'inactive', 'suspended', 'pending')),
  settings JSONB NOT NULL DEFAULT '{
    "allow_agent_visibility": true,
    "allow_csv_export": true,
    "timezone": "America/New_York",
    "report_retention_days": 365
  }'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_clients_code ON public.bpo_clients(client_code);
CREATE INDEX IF NOT EXISTS idx_bpo_clients_status ON public.bpo_clients(account_status);
CREATE INDEX IF NOT EXISTS idx_bpo_clients_country ON public.bpo_clients(country);

ALTER TABLE public.bpo_clients ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_clients service role access" ON public.bpo_clients;
CREATE POLICY "bpo_clients service role access" ON public.bpo_clients
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 2. Client Users (Links authenticated user profiles to client organization with RBAC)
CREATE TABLE IF NOT EXISTS public.bpo_client_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID NOT NULL REFERENCES public.bpo_clients(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'client_admin'
    CHECK (role IN ('client_admin', 'client_manager', 'client_viewer')),
  status TEXT NOT NULL DEFAULT 'active'
    CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(client_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_client_users_client ON public.bpo_client_users(client_id);
CREATE INDEX IF NOT EXISTS idx_bpo_client_users_user ON public.bpo_client_users(user_id);
CREATE INDEX IF NOT EXISTS idx_bpo_client_users_role ON public.bpo_client_users(role);

ALTER TABLE public.bpo_client_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_client_users service role access" ON public.bpo_client_users;
CREATE POLICY "bpo_client_users service role access" ON public.bpo_client_users
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. Enhance projects table with explicit BPO Client linkage
ALTER TABLE IF EXISTS public.projects
  ADD COLUMN IF NOT EXISTS bpo_client_id UUID REFERENCES public.bpo_clients(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_projects_bpo_client ON public.projects(bpo_client_id);

-- 4. Enable bpo_client_portal module flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_client_portal', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 5. Baseline Seed Client Accounts
INSERT INTO public.bpo_clients (
  id,
  client_code,
  company_name,
  legal_name,
  country,
  industry,
  primary_contact,
  contact_email,
  contact_phone,
  account_status,
  settings
) VALUES 
(
  '00000000-0000-0000-0000-000000000101',
  'THK-CLI-00001',
  'Aura Health Enterprises Inc.',
  'Aura Health Global Delivery Inc.',
  'United States',
  'Healthcare & Life Sciences',
  'Sarah Jenkins, VP Operational Delivery',
  'sarah.jenkins@aurahealth.com',
  '+1 (555) 342-9801',
  'active',
  '{"allow_agent_visibility": true, "allow_csv_export": true, "timezone": "America/New_York", "report_retention_days": 365}'::jsonb
),
(
  '00000000-0000-0000-0000-000000000102',
  'THK-CLI-00002',
  'Helios Renewable Energy Ltd',
  'Helios Power Systems UK Ltd',
  'United Kingdom',
  'Energy & CleanTech',
  'Alistair Wright, Head of Customer Operations',
  'a.wright@heliosenergy.co.uk',
  '+44 20 7946 0912',
  'active',
  '{"allow_agent_visibility": true, "allow_csv_export": true, "timezone": "Europe/London", "report_retention_days": 365}'::jsonb
)
ON CONFLICT (client_code) DO NOTHING;
