-- Additive BPO partner operations model. No client financial data is copied here.
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_partner_portal', TRUE), ('partner_centres', TRUE), ('partner_projects', TRUE), ('partner_agents', TRUE), ('partner_attendance', TRUE), ('partner_reports', TRUE)
ON CONFLICT (module_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.bpo_partners (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  partner_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 200),
  legal_name TEXT,
  contact_name TEXT,
  email TEXT,
  phone TEXT,
  address TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bpo_partner_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL DEFAULT 'partner_admin' CHECK (role IN ('partner_admin','operations_manager','centre_manager','team_leader','agent')),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (partner_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_permissions (
  permission_key TEXT PRIMARY KEY,
  description TEXT NOT NULL
);
INSERT INTO public.bpo_permissions(permission_key, description) VALUES
 ('partner.dashboard.view','View partner operational dashboard'),
 ('partner.projects.view','View assigned projects'),
 ('partner.projects.manage','Manage assigned project operations'),
 ('partner.centre.view','View assigned centres'),
 ('partner.agents.view','View partner agents'),
 ('partner.agents.manage','Manage partner agents'),
 ('partner.attendance.view','View partner attendance'),
 ('partner.productivity.view','View available productivity metrics'),
 ('partner.quality.view','View available quality metrics'),
 ('partner.training.view','View assigned training'),
 ('partner.documents.view','View partner-visible documents'),
 ('partner.tickets.view','View partner tickets'),
 ('partner.tickets.create','Create partner tickets'),
 ('partner.billing.view','View authorized partner payout statements only'),
 ('partner.payouts.view','View authorized partner payouts'),
 ('partner.reports.view','View authorized operational reports'),
 ('partner.meetings.view','View explicitly authorized partner meetings'),
 ('partner.meetings.rsvp','Respond to authorized partner meetings'),
 ('partner.training.manage','Update assigned training status'),
 ('partner.notifications.view','View partner notifications'),
 ('partner.settings.view','View partner settings')
ON CONFLICT (permission_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.bpo_partner_user_permissions (
  partner_user_id BIGINT NOT NULL REFERENCES public.bpo_partner_users(id) ON DELETE CASCADE,
  permission_key TEXT NOT NULL REFERENCES public.bpo_permissions(permission_key) ON DELETE CASCADE,
  PRIMARY KEY (partner_user_id, permission_key)
);

CREATE TABLE IF NOT EXISTS public.bpo_centres (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  name TEXT NOT NULL CHECK (char_length(name) BETWEEN 2 AND 200),
  location TEXT,
  contact_name TEXT,
  contact_phone TEXT,
  email TEXT,
  capacity INTEGER NOT NULL DEFAULT 0 CHECK (capacity >= 0),
  operating_hours TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.bpo_partner_projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  campaign_name TEXT,
  target TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','completed','suspended')),
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (partner_id, project_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_agents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  profile_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  employee_id TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT,
  phone TEXT,
  agent_role TEXT NOT NULL DEFAULT 'agent',
  joining_date DATE,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','inactive','on_leave','suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (partner_id, employee_id)
);

CREATE TABLE IF NOT EXISTS public.bpo_agent_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_project_id BIGINT NOT NULL REFERENCES public.bpo_partner_projects(id) ON DELETE CASCADE,
  assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  unassigned_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (agent_id, partner_project_id)
);

CREATE INDEX IF NOT EXISTS idx_bpo_partner_users_user ON public.bpo_partner_users(user_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centres_partner ON public.bpo_centres(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_projects_partner ON public.bpo_partner_projects(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_projects_project ON public.bpo_partner_projects(project_id);
CREATE INDEX IF NOT EXISTS idx_bpo_agents_partner ON public.bpo_agents(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_agents_centre ON public.bpo_agents(centre_id);
CREATE INDEX IF NOT EXISTS idx_bpo_assignments_project ON public.bpo_agent_assignments(partner_project_id);

DROP TRIGGER IF EXISTS trg_bpo_partners_updated_at ON public.bpo_partners;
CREATE TRIGGER trg_bpo_partners_updated_at BEFORE UPDATE ON public.bpo_partners FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_bpo_centres_updated_at ON public.bpo_centres;
CREATE TRIGGER trg_bpo_centres_updated_at BEFORE UPDATE ON public.bpo_centres FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
DROP TRIGGER IF EXISTS trg_bpo_agents_updated_at ON public.bpo_agents;
CREATE TRIGGER trg_bpo_agents_updated_at BEFORE UPDATE ON public.bpo_agents FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.bpo_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_partner_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_partner_user_permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_centres ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_partner_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_agent_assignments ENABLE ROW LEVEL SECURITY;

DO $$ DECLARE table_name TEXT; BEGIN
  FOREACH table_name IN ARRAY ARRAY['bpo_partners','bpo_partner_users','bpo_partner_user_permissions','bpo_centres','bpo_partner_projects','bpo_agents','bpo_agent_assignments'] LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', table_name || ' service role access', table_name);
    EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO service_role USING (true) WITH CHECK (true)', table_name || ' service role access', table_name);
  END LOOP;
END $$;
