-- Ticketing foundation. Additive and safe for existing accounts/modules.
INSERT INTO storage.buckets (id, name, public)
VALUES ('ticket-attachments', 'ticket-attachments', false)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.module_settings (
    module_key TEXT PRIMARY KEY,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    updated_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO public.module_settings (module_key, enabled)
VALUES ('tickets', TRUE)
ON CONFLICT (module_key) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number TEXT UNIQUE,
    requester_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    requester_role TEXT NOT NULL CHECK (requester_role IN ('client', 'partner', 'user')),
    subject TEXT NOT NULL CHECK (char_length(subject) BETWEEN 3 AND 200),
    category TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'assigned', 'in_progress', 'waiting_for_requester', 'resolved', 'closed')),
    description TEXT NOT NULL,
    related_project_id TEXT,
    related_invoice_id TEXT,
    related_plan_id TEXT,
    assigned_to BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    sla_due_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.ticket_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE RESTRICT,
    author_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    author_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    body TEXT NOT NULL,
    is_internal BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT ticket_message_author_check CHECK ((author_user_id IS NOT NULL) <> (author_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.ticket_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES public.tickets(id) ON DELETE RESTRICT,
    message_id BIGINT REFERENCES public.ticket_messages(id) ON DELETE RESTRICT,
    uploaded_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    uploaded_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    storage_path TEXT NOT NULL,
    file_name TEXT NOT NULL,
    content_type TEXT NOT NULL,
    file_size BIGINT NOT NULL CHECK (file_size > 0 AND file_size <= 10485760),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    recipient_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT NOT NULL,
    entity_type TEXT,
    entity_id TEXT,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT notification_recipient_check CHECK ((recipient_user_id IS NOT NULL) <> (recipient_admin_id IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    actor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
    action TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_tickets_requester_id ON public.tickets(requester_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status_priority ON public.tickets(status, priority);
CREATE INDEX IF NOT EXISTS idx_tickets_assigned_to ON public.tickets(assigned_to);
CREATE INDEX IF NOT EXISTS idx_tickets_created_at ON public.tickets(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_project_id ON public.tickets(related_project_id);
CREATE INDEX IF NOT EXISTS idx_ticket_messages_ticket_id ON public.ticket_messages(ticket_id, created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON public.notifications(recipient_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON public.audit_logs(entity_type, entity_id, created_at DESC);

DROP TRIGGER IF EXISTS trg_tickets_updated_at ON public.tickets;
CREATE TRIGGER trg_tickets_updated_at BEFORE UPDATE ON public.tickets FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ticket_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.module_settings ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Ticket service role access" ON public.tickets;
CREATE POLICY "Ticket service role access" ON public.tickets FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Ticket message service role access" ON public.ticket_messages;
CREATE POLICY "Ticket message service role access" ON public.ticket_messages FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Ticket attachment service role access" ON public.ticket_attachments;
CREATE POLICY "Ticket attachment service role access" ON public.ticket_attachments FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Notification service role access" ON public.notifications;
CREATE POLICY "Notification service role access" ON public.notifications FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Audit service role access" ON public.audit_logs;
CREATE POLICY "Audit service role access" ON public.audit_logs FOR ALL TO service_role USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Module settings service role access" ON public.module_settings;
CREATE POLICY "Module settings service role access" ON public.module_settings FOR ALL TO service_role USING (true) WITH CHECK (true);
