-- ==============================================================================
-- Migration: 20260927000000_bpo_accreditation_workflow.sql
-- Description: Thinkatic BPO Accreditation Real Workflow Architecture
--              Extends existing BPO partner application, document, and centre
--              tables to support the 8-stage Accreditation Lifecycle:
--              1. APPLICATION SUBMITTED
--              2. APPLICATION UNDER REVIEW
--              3. DOCUMENTS VERIFIED
--              4. INFRASTRUCTURE VERIFICATION
--              5. MANAGEMENT VERIFICATION
--              6. TRIAL / ASSESSMENT
--              7. DECISION
--              8. CENTRE ACTIVATED
-- ==============================================================================

-- 1. Enable module settings flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_accreditation_workflow', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. Add Accreditation Lifecycle columns to bpo_partner_applications
ALTER TABLE public.bpo_partner_applications
  ADD COLUMN IF NOT EXISTS accreditation_stages JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS management_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS decision_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS assessment_data JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS infrastructure_verification JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS management_verification JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS activated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS activated_by BIGINT,
  ADD COLUMN IF NOT EXISTS activation_reason TEXT;

-- 3. Enhance bpo_application_documents with versioning and review metadata
ALTER TABLE public.bpo_application_documents
  ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS file_size BIGINT,
  ADD COLUMN IF NOT EXISTS mime_type TEXT,
  ADD COLUMN IF NOT EXISTS storage_key TEXT,
  ADD COLUMN IF NOT EXISTS uploaded_by UUID,
  ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS reviewed_by_name TEXT,
  ADD COLUMN IF NOT EXISTS rejection_reason TEXT,
  ADD COLUMN IF NOT EXISTS is_current BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS document_name TEXT;

-- 4. BPO Partner Assessments Table (Trial / Assessment stage)
CREATE TABLE IF NOT EXISTS public.bpo_partner_assessments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_code TEXT UNIQUE NOT NULL, -- e.g. 'THK-ASM-00001'
  application_id BIGINT NOT NULL REFERENCES public.bpo_partner_applications(id) ON DELETE CASCADE,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE SET NULL,
  centre_id TEXT,
  assessment_type TEXT NOT NULL CHECK (assessment_type IN (
    'Technical Test',
    'Agent Readiness',
    'Process Simulation',
    'Voice/Communication Assessment',
    'Operational Readiness',
    'Pilot / Trial'
  )),
  project_name TEXT,
  scheduled_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  end_time TEXT NOT NULL,
  assessor_name TEXT NOT NULL,
  assessor_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  required_agents INTEGER NOT NULL DEFAULT 5,
  test_scope TEXT,
  technical_requirements TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'SCHEDULED' CHECK (status IN (
    'PLANNED',
    'SCHEDULED',
    'IN_PROGRESS',
    'SUBMITTED',
    'PASSED',
    'FAILED',
    'RESCHEDULED',
    'CANCELLED'
  )),
  score NUMERIC(5,2),
  result_notes TEXT,
  resubmission_allowed BOOLEAN NOT NULL DEFAULT TRUE,
  conducted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 5. Indexes for fast query lookups
CREATE INDEX IF NOT EXISTS idx_bpo_assessments_application ON public.bpo_partner_assessments(application_id);
CREATE INDEX IF NOT EXISTS idx_bpo_assessments_status ON public.bpo_partner_assessments(status);
CREATE INDEX IF NOT EXISTS idx_bpo_app_docs_application ON public.bpo_application_documents(application_id);
CREATE INDEX IF NOT EXISTS idx_bpo_app_docs_type ON public.bpo_application_documents(document_type);
