-- ==============================================================================
-- Migration: 20260920000000_create_bpo_partner_agreements.sql
-- Description: Thinkatic Global Delivery Partner Agreement workflow
--              Stores issued Agreements, versions, offline manual signed PDF uploads,
--              Admin reviews, approvals/rejections, and immutable legal records.
--              Legal Entity: Healweal LLC. Source of truth: Thinkatic Global Delivery
--              Partner Agreement.pdf (58 clauses + Schedules A-E).
-- ==============================================================================

-- 1. Enable bpo_partner_agreements module flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_partner_agreements', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. Partner Agreements Table
CREATE TABLE IF NOT EXISTS public.bpo_partner_agreements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_code TEXT UNIQUE NOT NULL, -- e.g. 'THK-GDP-00001'
  partner_id UUID REFERENCES public.bpo_partners(id),
  application_id BIGINT REFERENCES public.bpo_partner_applications(id),
  centre_id TEXT, -- Preserves existing Centre ID
  version TEXT NOT NULL DEFAULT '1.0',
  status TEXT NOT NULL DEFAULT 'agreement_ready' 
    CHECK (status IN ('draft', 'pending_admin_issuance', 'agreement_ready', 'awaiting_signed_upload', 'signed_agreement_submitted', 'admin_review', 'approved', 'rejected')),
  
  -- Partner Legal & Profile details (Pre-populated from onboarding)
  partner_legal_name TEXT NOT NULL,
  partner_trade_name TEXT,
  registration_number TEXT,
  registered_address TEXT,
  authorized_signatory_name TEXT,
  authorized_signatory_designation TEXT,
  contact_email TEXT,
  contact_phone TEXT,

  -- Thinkatic Legal Entity
  thinkatic_legal_entity TEXT NOT NULL DEFAULT 'Healweal LLC' CHECK (thinkatic_legal_entity = 'Healweal LLC'),
  thinkatic_signatory_name TEXT NOT NULL DEFAULT 'Harshad Chavandke',
  thinkatic_signatory_designation TEXT NOT NULL DEFAULT 'Director',
  
  -- Key Terms
  term_months INTEGER NOT NULL DEFAULT 11,
  royalty_percentage NUMERIC(5,2) NOT NULL DEFAULT 25.00,

  -- Uploaded Signed Agreement Document
  signed_document_url TEXT,
  signed_document_file_name TEXT,
  signed_document_file_size INTEGER,
  signed_submitted_at TIMESTAMPTZ,
  signed_submitted_by TEXT,

  -- Human Admin Review & Approval
  approved_at TIMESTAMPTZ,
  approved_by_admin_id BIGINT,
  approved_by_admin_name TEXT,
  rejection_reason TEXT,
  rejected_at TIMESTAMPTZ,
  rejected_by_admin_id BIGINT,

  -- Immutability Flag (Set to true once approved)
  is_immutable BOOLEAN NOT NULL DEFAULT FALSE,

  -- Complete Snapshot Data (Schedules A-E, operational profiles)
  template_data JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_partner_agreements_code ON public.bpo_partner_agreements(agreement_code);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_agreements_partner ON public.bpo_partner_agreements(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_agreements_status ON public.bpo_partner_agreements(status);
CREATE INDEX IF NOT EXISTS idx_bpo_partner_agreements_centre ON public.bpo_partner_agreements(centre_id);

-- 3. Agreement Submissions History Table (Preserves all historical uploads & reasons on resubmission)
CREATE TABLE IF NOT EXISTS public.bpo_agreement_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agreement_id BIGINT NOT NULL REFERENCES public.bpo_partner_agreements(id) ON DELETE CASCADE,
  submission_number INTEGER NOT NULL DEFAULT 1,
  file_name TEXT NOT NULL,
  file_url TEXT NOT NULL,
  file_size INTEGER,
  status TEXT NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review', 'approved', 'rejected')),
  rejection_reason TEXT,
  submitted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  submitted_by TEXT,
  reviewed_at TIMESTAMPTZ,
  reviewed_by_admin_id BIGINT
);

CREATE INDEX IF NOT EXISTS idx_bpo_agreement_submissions_agreement ON public.bpo_agreement_submissions(agreement_id);

-- Enable RLS
ALTER TABLE public.bpo_partner_agreements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bpo_agreement_submissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "bpo_partner_agreements service role access" ON public.bpo_partner_agreements;
CREATE POLICY "bpo_partner_agreements service role access" ON public.bpo_partner_agreements
  FOR ALL TO service_role USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "bpo_agreement_submissions service role access" ON public.bpo_agreement_submissions;
CREATE POLICY "bpo_agreement_submissions service role access" ON public.bpo_agreement_submissions
  FOR ALL TO service_role USING (true) WITH CHECK (true);
