-- ==============================================================================
-- Migration: 20260914000000_bpo_phase4_operations.sql
-- Description: Phase 4 - Attendance, Shift Foundation, Production Tracking,
--              Quality Assurance, Compliance Governance, and Operational CAPA
-- ==============================================================================

-- 1. Shift Management Foundation
CREATE TABLE IF NOT EXISTS public.bpo_shifts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift_name TEXT NOT NULL,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  partner_id UUID REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  start_time TIME NOT NULL DEFAULT '09:00:00',
  end_time TIME NOT NULL DEFAULT '18:00:00',
  timezone TEXT NOT NULL DEFAULT 'UTC',
  break_minutes INTEGER NOT NULL DEFAULT 60 CHECK (break_minutes >= 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_shifts_centre ON public.bpo_shifts(centre_id);
CREATE INDEX IF NOT EXISTS idx_bpo_shifts_partner ON public.bpo_shifts(partner_id);

ALTER TABLE public.bpo_shifts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_shifts service role access" ON public.bpo_shifts;
CREATE POLICY "bpo_shifts service role access" ON public.bpo_shifts
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 2. Agent Attendance Records
CREATE TABLE IF NOT EXISTS public.bpo_agent_attendance (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  shift_id BIGINT REFERENCES public.bpo_shifts(id) ON DELETE SET NULL,
  attendance_date DATE NOT NULL DEFAULT CURRENT_DATE,
  check_in_time TIMESTAMPTZ,
  check_out_time TIMESTAMPTZ,
  total_working_minutes INTEGER NOT NULL DEFAULT 0 CHECK (total_working_minutes >= 0),
  late_minutes INTEGER NOT NULL DEFAULT 0 CHECK (late_minutes >= 0),
  status TEXT NOT NULL DEFAULT 'PRESENT'
    CHECK (status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'LEAVE', 'WEEK_OFF', 'HOLIDAY', 'ON_DUTY')),
  remarks TEXT,
  correction_status TEXT NOT NULL DEFAULT 'none'
    CHECK (correction_status IN ('none', 'requested', 'approved', 'rejected')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(agent_id, attendance_date)
);

CREATE INDEX IF NOT EXISTS idx_bpo_attendance_centre_date ON public.bpo_agent_attendance(centre_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_bpo_attendance_partner_date ON public.bpo_agent_attendance(partner_id, attendance_date);
CREATE INDEX IF NOT EXISTS idx_bpo_attendance_agent ON public.bpo_agent_attendance(agent_id);
CREATE INDEX IF NOT EXISTS idx_bpo_attendance_status ON public.bpo_agent_attendance(status);

ALTER TABLE public.bpo_agent_attendance ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_agent_attendance service role access" ON public.bpo_agent_attendance;
CREATE POLICY "bpo_agent_attendance service role access" ON public.bpo_agent_attendance
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. Attendance Corrections Workflow
CREATE TABLE IF NOT EXISTS public.bpo_attendance_corrections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attendance_id BIGINT NOT NULL REFERENCES public.bpo_agent_attendance(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  original_check_in TIMESTAMPTZ,
  original_check_out TIMESTAMPTZ,
  original_status TEXT NOT NULL,
  requested_check_in TIMESTAMPTZ,
  requested_check_out TIMESTAMPTZ,
  requested_status TEXT NOT NULL CHECK (requested_status IN ('PRESENT', 'ABSENT', 'LATE', 'HALF_DAY', 'LEAVE', 'WEEK_OFF', 'HOLIDAY', 'ON_DUTY')),
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  review_notes TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_att_corr_partner ON public.bpo_attendance_corrections(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_att_corr_status ON public.bpo_attendance_corrections(status);

ALTER TABLE public.bpo_attendance_corrections ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_attendance_corrections service role access" ON public.bpo_attendance_corrections;
CREATE POLICY "bpo_attendance_corrections service role access" ON public.bpo_attendance_corrections
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. Process-Specific Production Tracking
CREATE TABLE IF NOT EXISTS public.bpo_production_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  process_type TEXT NOT NULL CHECK (process_type IN ('voice', 'chat', 'email', 'ticket', 'backoffice')),
  production_date DATE NOT NULL DEFAULT CURRENT_DATE,
  metrics JSONB NOT NULL DEFAULT '{}'::jsonb,
  units_completed NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (units_completed >= 0),
  productive_hours NUMERIC(6,2) NOT NULL DEFAULT 0 CHECK (productive_hours >= 0),
  productivity_rate NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (productivity_rate >= 0),
  source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'system_import')),
  status TEXT NOT NULL DEFAULT 'submitted' CHECK (status IN ('submitted', 'verified', 'rejected')),
  verified_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE(agent_id, project_id, production_date)
);

CREATE INDEX IF NOT EXISTS idx_bpo_prod_partner_date ON public.bpo_production_records(partner_id, production_date);
CREATE INDEX IF NOT EXISTS idx_bpo_prod_project_date ON public.bpo_production_records(project_id, production_date);
CREATE INDEX IF NOT EXISTS idx_bpo_prod_agent ON public.bpo_production_records(agent_id);

ALTER TABLE public.bpo_production_records ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_production_records service role access" ON public.bpo_production_records;
CREATE POLICY "bpo_production_records service role access" ON public.bpo_production_records
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. QA Scorecards (Configurable Criteria & Weights)
CREATE TABLE IF NOT EXISTS public.bpo_qa_scorecards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  process_type TEXT NOT NULL CHECK (process_type IN ('voice', 'chat', 'email', 'ticket', 'backoffice', 'general')),
  passing_threshold NUMERIC(5,2) NOT NULL DEFAULT 85.00 CHECK (passing_threshold BETWEEN 0 AND 100),
  criteria JSONB NOT NULL DEFAULT '[]'::jsonb,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_qa_scorecards_process ON public.bpo_qa_scorecards(process_type);

ALTER TABLE public.bpo_qa_scorecards ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_qa_scorecards service role access" ON public.bpo_qa_scorecards;
CREATE POLICY "bpo_qa_scorecards service role access" ON public.bpo_qa_scorecards
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 6. QA Evaluations (Interaction Quality & Defects)
CREATE TABLE IF NOT EXISTS public.bpo_qa_evaluations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  scorecard_id BIGINT NOT NULL REFERENCES public.bpo_qa_scorecards(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  project_id BIGINT NOT NULL REFERENCES public.projects(id) ON DELETE CASCADE,
  interaction_reference TEXT NOT NULL,
  evaluation_date DATE NOT NULL DEFAULT CURRENT_DATE,
  criteria_scores JSONB NOT NULL DEFAULT '{}'::jsonb,
  total_score NUMERIC(5,2) NOT NULL CHECK (total_score BETWEEN 0 AND 100),
  passed BOOLEAN NOT NULL,
  defects JSONB NOT NULL DEFAULT '[]'::jsonb,
  evaluator_feedback TEXT NOT NULL,
  internal_notes TEXT,
  status TEXT NOT NULL DEFAULT 'completed' CHECK (status IN ('completed', 'dispute_requested', 'revised')),
  evaluated_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_qa_eval_partner ON public.bpo_qa_evaluations(partner_id, evaluation_date);
CREATE INDEX IF NOT EXISTS idx_bpo_qa_eval_agent ON public.bpo_qa_evaluations(agent_id);
CREATE INDEX IF NOT EXISTS idx_bpo_qa_eval_project ON public.bpo_qa_evaluations(project_id);

ALTER TABLE public.bpo_qa_evaluations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_qa_evaluations service role access" ON public.bpo_qa_evaluations;
CREATE POLICY "bpo_qa_evaluations service role access" ON public.bpo_qa_evaluations
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 7. QA Review / Disputes
CREATE TABLE IF NOT EXISTS public.bpo_qa_disputes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  evaluation_id BIGINT NOT NULL REFERENCES public.bpo_qa_evaluations(id) ON DELETE CASCADE,
  agent_id BIGINT NOT NULL REFERENCES public.bpo_agents(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  dispute_reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'under_review', 'upheld', 'modified', 'rejected')),
  resolution_notes TEXT,
  reviewed_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bpo_qa_disputes_partner ON public.bpo_qa_disputes(partner_id);

ALTER TABLE public.bpo_qa_disputes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_qa_disputes service role access" ON public.bpo_qa_disputes;
CREATE POLICY "bpo_qa_disputes service role access" ON public.bpo_qa_disputes
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 8. Compliance Checks & Requirements
CREATE TABLE IF NOT EXISTS public.bpo_compliance_checks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  check_type TEXT NOT NULL CHECK (check_type IN ('training', 'certification', 'document', 'security', 'operational')),
  scope TEXT NOT NULL CHECK (scope IN ('centre', 'project', 'agent')),
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  requirement_description TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('compliant', 'non_compliant', 'pending', 'exception', 'expired')),
  due_date DATE,
  completed_at TIMESTAMPTZ,
  evidence_notes TEXT,
  evidence_url TEXT,
  verified_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_comp_partner ON public.bpo_compliance_checks(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_comp_status ON public.bpo_compliance_checks(status);

ALTER TABLE public.bpo_compliance_checks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_compliance_checks service role access" ON public.bpo_compliance_checks;
CREATE POLICY "bpo_compliance_checks service role access" ON public.bpo_compliance_checks
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 9. Compliance Exceptions
CREATE TABLE IF NOT EXISTS public.bpo_compliance_exceptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  check_id BIGINT NOT NULL REFERENCES public.bpo_compliance_checks(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
  reviewed_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  review_notes TEXT,
  valid_until DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_bpo_comp_exc_partner ON public.bpo_compliance_exceptions(partner_id);

ALTER TABLE public.bpo_compliance_exceptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_compliance_exceptions service role access" ON public.bpo_compliance_exceptions;
CREATE POLICY "bpo_compliance_exceptions service role access" ON public.bpo_compliance_exceptions
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 10. Corrective Actions (CAPA)
CREATE TABLE IF NOT EXISTS public.bpo_corrective_actions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action_code TEXT NOT NULL UNIQUE,
  related_entity_type TEXT NOT NULL CHECK (related_entity_type IN ('qa_evaluation', 'compliance_check', 'attendance')),
  related_entity_id BIGINT NOT NULL,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  centre_id BIGINT REFERENCES public.bpo_centres(id) ON DELETE SET NULL,
  agent_id BIGINT REFERENCES public.bpo_agents(id) ON DELETE SET NULL,
  issue_summary TEXT NOT NULL,
  action_required TEXT NOT NULL,
  owner_name TEXT NOT NULL,
  due_date DATE NOT NULL,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed', 'overdue', 'cancelled')),
  completion_date DATE,
  completion_notes TEXT,
  verified_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_capa_partner ON public.bpo_corrective_actions(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_capa_status ON public.bpo_corrective_actions(status);

ALTER TABLE public.bpo_corrective_actions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_corrective_actions service role access" ON public.bpo_corrective_actions;
CREATE POLICY "bpo_corrective_actions service role access" ON public.bpo_corrective_actions
  FOR ALL TO service_role USING (true) WITH CHECK (true);
