-- ==============================================================================
-- Migration: 20260917000000_bpo_phase7_capacity_marketplace.sql
-- Description: Phase 7 - BPO Capacity Marketplace Foundation
--              Normalized Centre Capacity, Client Capacity Requirements,
--              Deterministic Capacity Matches, and Concurrency-Safe Reservations.
-- ==============================================================================

-- 1. Enable bpo_capacity_marketplace module flag
INSERT INTO public.module_settings (module_key, enabled)
VALUES ('bpo_capacity_marketplace', TRUE)
ON CONFLICT (module_key) DO UPDATE SET enabled = TRUE;

-- 2. Normalized Centre Capacity Profiles
CREATE TABLE IF NOT EXISTS public.bpo_centre_capacity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  centre_id BIGINT UNIQUE NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  total_seats INTEGER NOT NULL DEFAULT 0 CHECK (total_seats >= 0),
  operational_seats INTEGER NOT NULL DEFAULT 0 CHECK (operational_seats >= 0),
  occupied_seats INTEGER NOT NULL DEFAULT 0 CHECK (occupied_seats >= 0),
  reserved_seats INTEGER NOT NULL DEFAULT 0 CHECK (reserved_seats >= 0),
  available_seats INTEGER NOT NULL DEFAULT 0 CHECK (available_seats >= 0),
  utilization_percentage NUMERIC(5,2) NOT NULL DEFAULT 0.00 CHECK (utilization_percentage >= 0),
  available_from DATE NOT NULL DEFAULT CURRENT_DATE,
  minimum_commitment INTEGER NOT NULL DEFAULT 5 CHECK (minimum_commitment > 0),
  maximum_commitment INTEGER NOT NULL DEFAULT 100 CHECK (maximum_commitment >= minimum_commitment),
  supported_processes JSONB NOT NULL DEFAULT '["Customer Support", "Inbound Voice", "Email & Chat"]'::jsonb,
  supported_channels JSONB NOT NULL DEFAULT '["Voice", "Email", "Chat"]'::jsonb,
  supported_languages JSONB NOT NULL DEFAULT '["English"]'::jsonb,
  supported_timezones JSONB NOT NULL DEFAULT '["UTC-5 (EST)", "UTC+0 (GMT)", "UTC+5:30 (IST)"]'::jsonb,
  supported_shifts JSONB NOT NULL DEFAULT '["US Shift (EST)", "UK Shift (GMT)", "24/7 Rotational"]'::jsonb,
  working_days JSONB NOT NULL DEFAULT '["Mon-Fri"]'::jsonb,
  capacity_status TEXT NOT NULL DEFAULT 'AVAILABLE'
    CHECK (capacity_status IN ('AVAILABLE', 'LIMITED', 'FULL', 'TEMPORARILY_UNAVAILABLE', 'INACTIVE')),
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT check_operational_total CHECK (operational_seats <= total_seats),
  CONSTRAINT check_occupied_reserved CHECK (occupied_seats + reserved_seats <= operational_seats)
);

CREATE INDEX IF NOT EXISTS idx_bpo_centre_cap_partner ON public.bpo_centre_capacity(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_cap_status ON public.bpo_centre_capacity(capacity_status);
CREATE INDEX IF NOT EXISTS idx_bpo_centre_cap_avail_seats ON public.bpo_centre_capacity(available_seats);

ALTER TABLE public.bpo_centre_capacity ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_centre_capacity service role access" ON public.bpo_centre_capacity;
CREATE POLICY "bpo_centre_capacity service role access" ON public.bpo_centre_capacity
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. Client Capacity Requirements
CREATE TABLE IF NOT EXISTS public.bpo_capacity_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requirement_code TEXT UNIQUE NOT NULL,
  client_id UUID NOT NULL REFERENCES public.bpo_clients(id) ON DELETE CASCADE,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE SET NULL,
  title TEXT NOT NULL CHECK (char_length(title) BETWEEN 3 AND 200),
  required_seats INTEGER NOT NULL CHECK (required_seats > 0),
  process_type TEXT NOT NULL,
  channels JSONB NOT NULL DEFAULT '["Voice"]'::jsonb,
  languages JSONB NOT NULL DEFAULT '["English"]'::jsonb,
  timezone TEXT NOT NULL DEFAULT 'UTC-5 (EST)',
  shift TEXT NOT NULL DEFAULT 'US Shift (EST)',
  location_requirement TEXT NOT NULL DEFAULT 'Any',
  start_date DATE NOT NULL,
  expected_duration_months INTEGER NOT NULL DEFAULT 6 CHECK (expected_duration_months > 0),
  minimum_experience_years INTEGER NOT NULL DEFAULT 1 CHECK (minimum_experience_years >= 0),
  certification_requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
  compliance_requirements JSONB NOT NULL DEFAULT '[]'::jsonb,
  working_days TEXT NOT NULL DEFAULT 'Mon-Fri',
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'DRAFT'
    CHECK (status IN ('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'MATCHING', 'MATCHED', 'ALLOCATED', 'CANCELLED', 'CLOSED')),
  created_by_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_cap_req_client ON public.bpo_capacity_requirements(client_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_req_status ON public.bpo_capacity_requirements(status);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_req_code ON public.bpo_capacity_requirements(requirement_code);

ALTER TABLE public.bpo_capacity_requirements ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_capacity_requirements service role access" ON public.bpo_capacity_requirements;
CREATE POLICY "bpo_capacity_requirements service role access" ON public.bpo_capacity_requirements
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. Deterministic Capacity Matches
CREATE TABLE IF NOT EXISTS public.bpo_capacity_matches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_code TEXT UNIQUE NOT NULL,
  requirement_id BIGINT NOT NULL REFERENCES public.bpo_capacity_requirements(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  matched_capacity INTEGER NOT NULL CHECK (matched_capacity > 0),
  matching_criteria JSONB NOT NULL DEFAULT '{}'::jsonb,
  match_status TEXT NOT NULL DEFAULT 'PROPOSED'
    CHECK (match_status IN ('PROPOSED', 'UNDER_REVIEW', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED')),
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  selected_by BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  selected_at TIMESTAMPTZ DEFAULT NOW(),
  decision_source TEXT NOT NULL DEFAULT 'HUMAN_OPERATIONS'
    CHECK (decision_source = 'HUMAN_OPERATIONS'),
  score_type TEXT NOT NULL DEFAULT 'INFORMATIONAL_COMPATIBILITY',
  automatic_selection BOOLEAN NOT NULL DEFAULT FALSE
    CHECK (automatic_selection = FALSE),
  decision_notes TEXT,
  reviewed_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  reviewed_at TIMESTAMPTZ,
  rejection_reason TEXT,
  internal_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_cap_match_req ON public.bpo_capacity_matches(requirement_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_match_centre ON public.bpo_capacity_matches(centre_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_match_partner ON public.bpo_capacity_matches(partner_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_match_status ON public.bpo_capacity_matches(match_status);

ALTER TABLE public.bpo_capacity_matches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_capacity_matches service role access" ON public.bpo_capacity_matches;
CREATE POLICY "bpo_capacity_matches service role access" ON public.bpo_capacity_matches
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 5. Concurrency-Safe Capacity Reservations
CREATE TABLE IF NOT EXISTS public.bpo_capacity_reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reservation_code TEXT UNIQUE NOT NULL,
  requirement_id BIGINT NOT NULL REFERENCES public.bpo_capacity_requirements(id) ON DELETE CASCADE,
  match_id BIGINT NOT NULL REFERENCES public.bpo_capacity_matches(id) ON DELETE CASCADE,
  centre_id BIGINT NOT NULL REFERENCES public.bpo_centres(id) ON DELETE CASCADE,
  partner_id UUID NOT NULL REFERENCES public.bpo_partners(id) ON DELETE CASCADE,
  reserved_seats INTEGER NOT NULL CHECK (reserved_seats > 0),
  status TEXT NOT NULL DEFAULT 'ACTIVE'
    CHECK (status IN ('ACTIVE', 'CONVERTED', 'RELEASED', 'EXPIRED')),
  reservation_start DATE NOT NULL DEFAULT CURRENT_DATE,
  reservation_expires_at TIMESTAMPTZ NOT NULL,
  released_at TIMESTAMPTZ,
  release_reason TEXT,
  created_by_admin_id BIGINT REFERENCES public.admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_bpo_cap_res_req ON public.bpo_capacity_reservations(requirement_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_res_centre ON public.bpo_capacity_reservations(centre_id);
CREATE INDEX IF NOT EXISTS idx_bpo_cap_res_status ON public.bpo_capacity_reservations(status);

ALTER TABLE public.bpo_capacity_reservations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "bpo_capacity_reservations service role access" ON public.bpo_capacity_reservations;
CREATE POLICY "bpo_capacity_reservations service role access" ON public.bpo_capacity_reservations
  FOR ALL TO service_role USING (true) WITH CHECK (true);
