import { useEffect, useState, type FormEvent } from "react";
import { useLocation } from "wouter";
import { Activity, BarChart3, Building2, CalendarDays, ClipboardList, FileText, FolderKanban, GraduationCap, LogOut, Plus, RefreshCw, ShieldCheck, Users, Video, WalletCards } from "lucide-react";

interface PartnerData { id: string; partner_code: string; name: string; legal_name: string | null; contact_name: string | null; status: string; }
interface DashboardData { metrics: { activeProjects: number; centres: number; activeAgents: number; todaysAttendance: number; openTickets: number; activeAssignments: number }; projects: any[]; centres: any[]; unavailable: string[]; unreadNotifications: number; }
interface Centre { id: number; name: string; location: string | null; capacity: number; status: string; }
interface Agent { id: number; employee_id: string; name: string; email: string | null; status: string; bpo_centres?: { name: string } | null; }

const tabs = [
  ["overview", "Dashboard", Activity], ["projects", "Projects", FolderKanban], ["centres", "Centres", Building2],
  ["agents", "Agents", Users], ["attendance", "Attendance", CalendarDays], ["documents", "Documents", FileText], ["meetings", "Meetings", Video],
  ["training", "Training", GraduationCap], ["productivity", "Productivity", BarChart3], ["quality", "Quality", ShieldCheck], ["payouts", "Payouts", WalletCards], ["reports", "Reports", BarChart3], ["tickets", "Tickets", ClipboardList],
] as const;

function api(path: string, options: RequestInit = {}) {
  const token = localStorage.getItem("user_token");
  return fetch(`/api${path}`, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}`, ...(options.headers || {}) } });
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">{label}</p><p className="mt-3 text-3xl font-black text-slate-950">{value}</p></div>; }
function Status({ value }: { value: string }) { return <span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold capitalize text-blue-700">{value.replaceAll("_", " ")}</span>; }

export default function PartnerDashboardPage() {
  const [, setLocation] = useLocation();
  const [tab, setTab] = useState<(typeof tabs)[number][0]>("overview");
  const [partner, setPartner] = useState<PartnerData | null>(null);
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [centres, setCentres] = useState<Centre[]>([]);
  const [agents, setAgents] = useState<Agent[]>([]);
  const [projects, setProjects] = useState<any[]>([]);
  const [attendance, setAttendance] = useState<any[]>([]);
  const [tickets, setTickets] = useState<any[]>([]);
  const [documents, setDocuments] = useState<any[]>([]);
  const [meetings, setMeetings] = useState<any[]>([]);
  const [training, setTraining] = useState<any[]>([]);
  const [productivity, setProductivity] = useState<any | null>(null);
  const [quality, setQuality] = useState<any | null>(null);
  const [payouts, setPayouts] = useState<any[]>([]);
  const [reports, setReports] = useState<any | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [centreForm, setCentreForm] = useState({ name: "", location: "", capacity: "" });
  const [agentForm, setAgentForm] = useState({ employeeId: "", name: "", email: "", centreId: "" });
  const [saving, setSaving] = useState(false);
  const [disabled, setDisabled] = useState(false);

  async function load() {
    setLoading(true); setError("");
    try {
      const profileResponse = await api("/partner/profile");
      const profileBody = await profileResponse.json().catch(() => ({}));
      if (profileResponse.status === 401) { setLocation("/login?returnTo=/partner"); return; }
      if (profileResponse.status === 503) { setDisabled(true); setError(profileBody.error || profileBody.message || "BPO partner portal is currently disabled"); return; }
      if (profileResponse.status === 403) throw new Error(profileBody.error || profileBody.message || "BPO partner access required");
      if (!profileResponse.ok) throw new Error("Unable to load partner profile");
      const responses = await Promise.all([api("/partner/dashboard"), api("/partner/centres"), api("/partner/agents"), api("/partner/projects"), api("/partner/attendance"), api("/partner/tickets")]);
      const bodies = await Promise.all(responses.map(async (response) => ({ response, body: await response.json().catch(() => ({})) })));
      const failed = bodies.find(({ response }) => response.status === 401 || response.status === 403 || response.status === 503);
      if (failed?.response.status === 401) { setLocation("/login?returnTo=/partner"); return; }
      if (failed) throw new Error(failed.body.error || failed.body.message || `Partner portal unavailable (${failed.response.status})`);
      if (bodies.some(({ response }) => !response.ok)) throw new Error("Unable to load partner operations");
      setPartner(profileBody); setDashboard(bodies[0].body); setCentres(bodies[1].body); setAgents(bodies[2].body); setProjects(bodies[3].body); setAttendance(bodies[4].body); setTickets(bodies[5].body);
      const optional = await Promise.all(["/partner/documents", "/partner/meetings", "/partner/training", "/partner/productivity", "/partner/quality", "/partner/payout-statements", "/partner/reports"].map(async (path) => { const response = await api(path); return { response, body: await response.json().catch(() => ({})) }; }));
      setDocuments(optional[0].response.ok ? optional[0].body : []); setMeetings(optional[1].response.ok ? optional[1].body : []); setTraining(optional[2].response.ok ? optional[2].body : []); setProductivity(optional[3].response.ok ? optional[3].body : null); setQuality(optional[4].response.ok ? optional[4].body : null); setPayouts(optional[5].response.ok ? optional[5].body : []); setReports(optional[6].response.ok ? optional[6].body : null);
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load partner operations"); } finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, []);
  async function createCentre(event: FormEvent) { event.preventDefault(); setSaving(true); const response = await api("/partner/centres", { method: "POST", body: JSON.stringify(centreForm) }); if (!response.ok) setError((await response.json()).error || "Unable to create centre"); else { setCentreForm({ name: "", location: "", capacity: "" }); await load(); } setSaving(false); }
  async function createAgent(event: FormEvent) { event.preventDefault(); setSaving(true); const response = await api("/partner/agents", { method: "POST", body: JSON.stringify(agentForm) }); if (!response.ok) setError((await response.json()).error || "Unable to create agent"); else { setAgentForm({ employeeId: "", name: "", email: "", centreId: "" }); await load(); } setSaving(false); }
  function logout() { localStorage.removeItem("user_token"); localStorage.removeItem("user_profile"); window.location.href = "/login"; }

  if (disabled) return <div className="flex min-h-screen items-center justify-center bg-slate-50 px-5 text-center text-slate-950"><div className="max-w-md rounded-2xl border border-amber-200 bg-white p-8 shadow-sm"><ShieldCheck className="mx-auto text-amber-600" size={28} /><h1 className="mt-4 text-xl font-black">Partner portal unavailable</h1><p className="mt-2 text-sm text-slate-600">{error}</p></div></div>;
  return <div className="min-h-screen bg-slate-50 text-slate-950">
    <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><p className="text-[10px] font-black uppercase tracking-[0.25em] text-blue-700">Thinkatic Operations</p><h1 className="mt-1 text-xl font-black">BPO Partner Portal</h1></div><div className="flex items-center gap-3"><div className="hidden text-right sm:block"><p className="text-sm font-bold">{partner?.name || "Partner workspace"}</p><p className="text-xs text-slate-500">{partner?.partner_code || "Loading"}</p></div><button onClick={logout} className="rounded-xl border border-slate-200 p-2 text-slate-600 hover:bg-slate-50" title="Sign out"><LogOut size={16} /></button></div></div></header>
    <div className="mx-auto flex max-w-7xl flex-col gap-6 px-5 py-6 lg:flex-row"><aside className="lg:w-56"><nav className="flex gap-2 overflow-x-auto lg:flex-col">{tabs.map(([id, label, Icon]) => <button key={id} onClick={() => setTab(id)} className={`flex shrink-0 items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm font-bold ${tab === id ? "bg-blue-700 text-white" : "text-slate-600 hover:bg-white"}`}><Icon size={16} />{label}</button>)}</nav></aside><main className="min-w-0 flex-1">{error && <div className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</div>}{loading ? <div className="rounded-2xl border border-slate-200 bg-white p-10 text-center text-sm text-slate-500">Loading operational data...</div> : <>
      {tab === "overview" && dashboard && <section><div className="mb-6 flex items-end justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-blue-700">Operational overview</p><h2 className="mt-2 text-3xl font-black">Good morning, {partner?.contact_name || partner?.name}</h2></div><button onClick={() => void load()} className="rounded-xl border border-slate-200 bg-white p-2 text-slate-600" title="Refresh"><RefreshCw size={16} /></button></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"> <Metric label="Active projects" value={dashboard.metrics.activeProjects} /><Metric label="Centres" value={dashboard.metrics.centres} /><Metric label="Active agents" value={dashboard.metrics.activeAgents} /><Metric label="Today's attendance" value={dashboard.metrics.todaysAttendance} /><Metric label="Active assignments" value={dashboard.metrics.activeAssignments} /><Metric label="Open tickets" value={dashboard.metrics.openTickets} /><Metric label="Documents" value={documents.length} /><Metric label="Upcoming meetings" value={meetings.filter((meeting) => meeting.status !== "completed" && meeting.status !== "cancelled").length} /><Metric label="Training programs" value={training.length} /><Metric label="Payout statements" value={payouts.length} /></div><div className="mt-6 grid gap-5 xl:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-black">Assigned projects</h3>{dashboard.projects.length ? dashboard.projects.map((item) => <div key={item.id} className="mt-4 flex items-center justify-between border-b border-slate-100 pb-3"><div><p className="font-bold">{item.projects?.name || "Assigned project"}</p><p className="text-xs text-slate-500">{item.campaign_name || "Operational campaign"}</p></div><Status value={item.status} /></div>) : <p className="mt-4 text-sm text-slate-500">No assigned projects yet.</p>}</div><div className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-black text-amber-950">Data availability</h3><p className="mt-2 text-sm text-amber-800">Productivity and quality values appear only when source records exist.</p><div className="mt-4 flex flex-wrap gap-2">{dashboard.unavailable.map((item) => <span key={item} className="rounded-full bg-white px-3 py-1 text-xs font-bold capitalize text-amber-800">{item} unavailable</span>)}{productivity?.dataAvailable === false && <span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-amber-800">productivity unavailable</span>}{quality?.dataAvailable === false && <span className="rounded-full bg-white px-3 py-1 text-xs font-bold text-amber-800">quality unavailable</span>}</div></div></div></section>}
      {tab === "projects" && <section><h2 className="mb-5 text-2xl font-black">Assigned projects</h2>{projects.length ? <div className="grid gap-4 md:grid-cols-2">{projects.map((item) => <div key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between gap-3"><h3 className="font-black">{item.projects?.name || "Project"}</h3><Status value={item.status} /></div><p className="mt-2 text-sm text-slate-500">Campaign: {item.campaign_name || "Not specified"}</p><p className="mt-4 text-xs font-bold text-slate-500">Progress {item.projects?.progress_percent ?? 0}%</p></div>)}</div> : <Empty text="No projects have been assigned to this partner." />}</section>}
      {tab === "centres" && <section><div className="mb-5 flex items-center justify-between"><h2 className="text-2xl font-black">Centres</h2><span className="text-sm text-slate-500">{centres.length} assigned</span></div><form onSubmit={createCentre} className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-4"><input required placeholder="Centre name" value={centreForm.name} onChange={(event) => setCentreForm({ ...centreForm, name: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input placeholder="Location" value={centreForm.location} onChange={(event) => setCentreForm({ ...centreForm, location: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input type="number" min="0" placeholder="Capacity" value={centreForm.capacity} onChange={(event) => setCentreForm({ ...centreForm, capacity: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><button disabled={saving} className="flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-3 py-2 text-sm font-bold text-white"><Plus size={15} /> Add centre</button></form><div className="grid gap-4 md:grid-cols-2">{centres.map((centre) => <div key={centre.id} className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{centre.name}</h3><Status value={centre.status} /></div><p className="mt-2 text-sm text-slate-500">{centre.location || "Location not provided"}</p><p className="mt-4 text-xs font-bold uppercase tracking-wider text-slate-500">Capacity: {centre.capacity}</p></div>)}</div>{!centres.length && <Empty text="No centres assigned yet." />}</section>}
      {tab === "agents" && <section><h2 className="mb-5 text-2xl font-black">Agents</h2><form onSubmit={createAgent} className="mb-5 grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-4"><input required placeholder="Employee ID" value={agentForm.employeeId} onChange={(event) => setAgentForm({ ...agentForm, employeeId: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input required placeholder="Name" value={agentForm.name} onChange={(event) => setAgentForm({ ...agentForm, name: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><input type="email" placeholder="Email" value={agentForm.email} onChange={(event) => setAgentForm({ ...agentForm, email: event.target.value })} className="rounded-xl border border-slate-200 px-3 py-2 text-sm" /><button disabled={saving} className="flex items-center justify-center gap-2 rounded-xl bg-blue-700 px-3 py-2 text-sm font-bold text-white"><Plus size={15} /> Add agent</button></form><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Employee</th><th className="px-4 py-3">Name</th><th className="px-4 py-3">Centre</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{agents.map((agent) => <tr key={agent.id} className="border-t border-slate-100"><td className="px-4 py-3 font-mono text-xs">{agent.employee_id}</td><td className="px-4 py-3 font-bold">{agent.name}</td><td className="px-4 py-3 text-slate-500">{agent.bpo_centres?.name || "Unassigned"}</td><td className="px-4 py-3"><Status value={agent.status} /></td></tr>)}</tbody></table>{!agents.length && <Empty text="No agents assigned yet." />}</div></section>}
      {tab === "attendance" && <section><h2 className="mb-5 text-2xl font-black">Attendance</h2>{attendance.length ? <div className="rounded-2xl border border-slate-200 bg-white p-5">{attendance.map((row) => <div key={row.id} className="flex justify-between border-b border-slate-100 py-3 text-sm"><span>{row.date}</span><Status value={row.status} /><span className="text-slate-500">{row.duration_minutes || 0} minutes</span></div>)}</div> : <Empty text="No attendance records are available for assigned agents." />}</section>}
      {tab === "documents" && <section><h2 className="mb-5 text-2xl font-black">Partner documents</h2>{documents.length ? <div className="grid gap-4 md:grid-cols-2">{documents.map((document) => <div key={document.id} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-black">{document.original_file_name}</h3><p className="mt-2 text-sm text-slate-500">{document.category} · Shared with this partner</p></div>)}</div> : <Empty text="No documents have been explicitly shared with this partner." />}</section>}
      {tab === "meetings" && <section><h2 className="mb-5 text-2xl font-black">Authorized meetings</h2>{meetings.length ? meetings.map((meeting) => <div key={meeting.id} className="mb-3 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{meeting.title}</h3><Status value={meeting.status} /></div><p className="mt-2 text-sm text-slate-500">{new Date(meeting.starts_at).toLocaleString()} · {meeting.agenda || "No partner-visible agenda"}</p></div>) : <Empty text="No meetings are explicitly authorized for this partner." />}</section>}
      {tab === "training" && <section><h2 className="mb-5 text-2xl font-black">Training</h2>{training.length ? training.map((program) => <div key={program.id} className="mb-3 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{program.title}</h3><Status value={program.status} /></div><p className="mt-2 text-sm text-slate-500">Completion: {program.completion_percent}% · {(program.bpo_training_assignments || []).length} assigned agents</p></div>) : <Empty text="No training programs are assigned to this partner." />}</section>}
      {tab === "productivity" && <section><h2 className="mb-5 text-2xl font-black">Productivity</h2>{productivity?.dataAvailable ? <div className="grid gap-4 sm:grid-cols-3"><Metric label="Working minutes" value={productivity.totals.workingMinutes} /><Metric label="Tasks completed" value={productivity.totals.tasksCompleted} /><Metric label="Tickets handled" value={productivity.totals.ticketsHandled} /></div> : <Empty text="No productivity data available." />}</section>}
      {tab === "quality" && <section><h2 className="mb-5 text-2xl font-black">Quality</h2>{quality?.dataAvailable ? <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-slate-500">Average score</p><p className="mt-3 text-4xl font-black">{quality.averageScore}</p><p className="mt-2 text-sm text-slate-500">{quality.evaluations.length} partner-visible evaluations</p></div> : <Empty text="No quality data available." />}</section>}
      {tab === "payouts" && <section><h2 className="mb-5 text-2xl font-black">Payout statements</h2>{payouts.length ? payouts.map((statement) => <div key={statement.id} className="mb-3 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{statement.statement_number}</h3><Status value={statement.status} /></div><p className="mt-2 text-sm text-slate-500">Period {statement.period_start} to {statement.period_end} · Approved: ${Number(statement.approved_amount).toFixed(2)}</p></div>) : <Empty text="No payout statements are available." />}</section>}
      {tab === "reports" && <section><h2 className="mb-5 text-2xl font-black">Reports</h2>{reports?.reports ? <div className="grid gap-3 md:grid-cols-2">{Object.entries(reports.reports).map(([name, report]: [string, any]) => <div key={name} className="rounded-2xl border border-slate-200 bg-white p-5"><h3 className="font-black capitalize">{name}</h3><p className="mt-2 text-sm text-slate-500">{report.dataAvailable ? `${report.count ?? "Data"} records available` : report.reason || "No data available"}</p></div>)}</div> : <Empty text="No partner reports are available." />}</section>}
      {tab === "tickets" && <section><h2 className="mb-5 text-2xl font-black">Partner tickets</h2>{tickets.length ? tickets.map((ticket) => <div key={ticket.id} className="mb-3 rounded-2xl border border-slate-200 bg-white p-5"><div className="flex justify-between"><h3 className="font-black">{ticket.subject}</h3><Status value={ticket.status} /></div><p className="mt-2 text-xs text-slate-500">{ticket.ticket_number} · {ticket.category}</p></div>) : <Empty text="No partner tickets yet. Use Support Tickets to create an operational request." />}</section>}
    </>}</main></div></div>;
}
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-sm text-slate-500">{text}</div>; }
